-- insert apis
INSERT INTO apis (name, description, base_url, documentation, response_type, collection_date, authentication, version, institution_id)
VALUES('Cadprev', 'Dados sobre o Sistema de Informações dos Regimes Públicos de Previdência Social.', 'https://apicadprev.economia.gov.br/', 'https://apicadprev.economia.gov.br/api-docs/#/', 'JSON', '2023-09-26', 'N', '1.0.0', 1);

-- insert institutuions
INSERT INTO institutions (name, acronym)
VALUES('CADPREV - Sistema de Informações dos Regimes Públicos de Previdência Social', 'CADPREV');

-- insert endpoints 

INSERT INTO api_endpoints (id, api_id, name, url, description, example, api_responses_id)
VALUES
(1, 'Aplicacoes Resgate', '/DAIR_APLICACOES_RESGATE', 'Seleciona registro da tabela /DAIR_APLICACOES_RESGATE', '/DAIR_APLICACOES_RESGATE', 1),
(1, 'Carteira', '/DAIR_CARTEIRA', 'Seleciona registro da tabela /DAIR_CARTEIRA', '/DAIR_CARTEIRA', 2),
(1, 'Forma Gestao', '/DAIR_FORMA_GESTAO', 'Seleciona registro da tabela /DAIR_FORMA_GESTAO', '/DAIR_FORMA_GESTAO', 3),
(1, 'Fundo inverstimentos analisados', '/DAIR_FUNDO_INVEST_ANALISADOS', 'Seleciona registro da tabela /DAIR_FUNDO_INVEST_ANALISADOS', '/DAIR_FUNDO_INVEST_ANALISADOS', 4),
(1, 'Governanca', '/DAIR_GOVERNANCA', 'Seleciona registro da tabela /DAIR_GOVERNANCA', '/DAIR_GOVERNANCA', 5),
(1, 'Identificacao', '/DAIR_IDENTIFICACAO', 'Seleciona registro da tabela /DAIR_IDENTIFICACAO', '/DAIR_IDENTIFICACAO', 6),
(1, 'Instituição Credenciada', '/DAIR_INSTITUICAO_CREDENCIADA', 'Seleciona registro da tabela /DAIR_INSTITUICAO_CREDENCIADA', '/DAIR_INSTITUICAO_CREDENCIADA', 7),
(1, 'Regime Ata', '/DAIR_REGIME_ATA', 'Seleciona registro da tabela /DAIR_REGIME_ATA', '/DAIR_REGIME_ATA', 8),
(1, 'DEMONSTRATIVO DE INFORMAÇÕES PREVIDENCIÁRIAS E REPASSES', '/DIPR', 'Seleciona registro da tabela /DIPR', '/DIPR', 9),
(1, 'Base Calculo Armotizacao', '/DRAA_BASE_CALCULO_AMORTIZACAO', 'Seleciona registro da tabela /DRAA_BASE_CALCULO_AMORTIZACAO', '/DRAA_BASE_CALCULO_AMORTIZACAO', 10),
(1, 'Base Calculo Ente', '/DRAA_BASE_CALCULO_ENTE', 'Seleciona registro da tabela /DRAA_BASE_CALCULO_ENTE', '/DRAA_BASE_CALCULO_ENTE', 11),
(1, 'Comparativo Avaliacao', '/DRAA_COMPARATIVO_AVALIACAO', 'Seleciona registro da tabela /DRAA_COMPARATIVO_AVALIACAO', '/DRAA_COMPARATIVO_AVALIACAO', 12),
(1, 'Comparativo Receita', '/DRAA_COMPARATIVO_RECEITA', 'Seleciona registro da tabela /DRAA_COMPARATIVO_RECEITA', '/DRAA_COMPARATIVO_RECEITA', 13),
(1, 'Contribuicao', '/DRAA_CONTRIBUICAO', 'Seleciona registro da tabela /DRAA_CONTRIBUICAO', '/DRAA_CONTRIBUICAO', 14),
(1, 'Custo Normal Beneficios capital', '/DRAA_CUSTO_NORMAL_BENEF_CAPIT', 'Seleciona registro da tabela /DRAA_CUSTO_NORMAL_BENEF_CAPIT', '/DRAA_CUSTO_NORMAL_BENEF_CAPIT', 15),
(1, 'Custo normal beneficio cob', '/DRAA_CUSTO_NORMAL_BENEF_COB', 'Seleciona registro da tabela /DRAA_CUSTO_NORMAL_BENEF_COB', '/DRAA_CUSTO_NORMAL_BENEF_COB', 16),
(1, 'Custo normal Rep Aposentadoria', '/DRAA_CUSTO_NORMAL_REP_APOS', 'Seleciona registro da tabela /DRAA_CUSTO_NORMAL_REP_APOS', '/DRAA_CUSTO_NORMAL_REP_APOS', 17),
(1, 'Custo Normal Rep Auxilio', '/DRAA_CUSTO_NORMAL_REP_AUX', 'Seleciona registro da tabela /DRAA_CUSTO_NORMAL_REP_AUX', '/DRAA_CUSTO_NORMAL_REP_AUX', 18),
(1, 'Dados consolidados', '/DRAA_DADOS_CONSOLIDADOS', 'Seleciona registro da tabela /DRAA_DADOS_CONSOLIDADOS', '/DRAA_DADOS_CONSOLIDADOS', 19),
(1, 'Encaminhamento', '/DRAA_ENCAMINHAMENTO', 'Seleciona registro da tabela /DRAA_ENCAMINHAMENTO', '/DRAA_ENCAMINHAMENTO', 20),
(1, 'Estatistica', '/DRAA_ESTATISTICA', 'Seleciona registro da tabela /DRAA_ESTATISTICA', '/DRAA_ESTATISTICA', 21),
(1, 'Fluxo Atuarial', '/DRAA_FLUXO_ATUARIAL', 'Seleciona registro da tabela /DRAA_FLUXO_ATUARIAL', '/DRAA_FLUXO_ATUARIAL', 22),
(1, 'Forma Amortizacao', '/DRAA_FORMA_AMORTIZACAO', 'Seleciona registro da tabela /DRAA_FORMA_AMORTIZACAO', '/DRAA_FORMA_AMORTIZACAO', 23),
(1, 'Hipotese Atuarial', '/DRAA_HIPOTESE_ATUARIAL', 'Seleciona registro da tabela /DRAA_HIPOTESE_ATUARIAL', '/DRAA_HIPOTESE_ATUARIAL', 24),
(1, 'Hipotese Biometrica', '/DRAA_HIPOTESE_BIOMETRICA', 'Seleciona registro da tabela /DRAA_HIPOTESE_BIOMETRICA', '/DRAA_HIPOTESE_BIOMETRICA', 25),
(1, 'Notificacao', '/DRAA_NOTIFICACAO', 'Seleciona registro da tabela /DRAA_NOTIFICACAO', '/DRAA_NOTIFICACAO', 26),
(1, 'Orgao Entidade', '/DRAA_ORGAO_ENTIDADE', 'Seleciona registro da tabela /DRAA_ORGAO_ENTIDADE', '/DRAA_ORGAO_ENTIDADE', 27),
(1, 'Parecer Atuarial', '/DRAA_PARECER_ATUARIAL', 'Seleciona registro da tabela /DRAA_PARECER_ATUARIAL', '/DRAA_PARECER_ATUARIAL', 28),
(1, 'Plano Amortizacao', '/DRAA_PLANO_AMORTIZACAO', 'Seleciona registro da tabela /DRAA_PLANO_AMORTIZACAO', '/DRAA_PLANO_AMORTIZACAO', 29),
(1, 'Plano Amortizacao Deficit', '/DRAA_PLANO_AMORTIZACAO_DEFICIT', 'Seleciona registro da tabela /DRAA_PLANO_AMORTIZACAO_DEFICIT', '/DRAA_PLANO_AMORTIZACAO_DEFICIT', 30),
(1, 'Plano Beneficio', '/DRAA_PLANO_BENEFICIO', 'Seleciona registro da tabela /DRAA_PLANO_BENEFICIO', '/DRAA_PLANO_BENEFICIO', 31),
(1, 'Plano Custeio', '/DRAA_PLANO_CUSTEIO', 'Seleciona registro da tabela /DRAA_PLANO_CUSTEIO', '/DRAA_PLANO_CUSTEIO', 32),
(1, 'Retificacao Notificacao', '/DRAA_RETIFICACAO_NOTIFICACAO', 'Seleciona registro da tabela /DRAA_RETIFICACAO_NOTIFICACAO', '/DRAA_RETIFICACAO_NOTIFICACAO', 33),
(1, 'Segregacao Massa', '/DRAA_SEGREGACAO_MASSA', 'Seleciona registro da tabela /DRAA_SEGREGACAO_MASSA', '/DRAA_SEGREGACAO_MASSA', 34),
(1, 'Valores Compromissos', '/DRAA_VALORES_COMPROMISSOS', 'Seleciona registro da tabela /DRAA_VALORES_COMPROMISSOS', '/DRAA_VALORES_COMPROMISSOS', 35),
(1, 'Aliquota', '/RPPS_ALIQUOTA', 'Seleciona registro da tabela /RPPS_ALIQUOTA', '/RPPS_ALIQUOTA', 36),
(1, 'CRP', '/RPPS_CRP', 'Seleciona registro da tabela /RPPS_CRP', '/RPPS_CRP', 37),
(1, 'Regime Previdenciario', '/RPPS_REGIME_PREVIDENCIARIO', 'Seleciona registro da tabela /RPPS_REGIME_PREVIDENCIARIO', '/RPPS_REGIME_PREVIDENCIARIO', 38);

-- insert endpoints_parameters
INSERT INTO endpoint_parameters (endpoints_id, parameter_id, required) VALUES
(1, 1, 'N'),
(1, 2, 'N'),
(1, 3, 'N'),
(1, 4, 'N'),
(1, 5, 'N'),
(1, 6, 'N'),
(1, 7, 'N'),
(1, 8, 'N'),
(1, 9, 'N'),
(1, 10, 'N'),
(1, 11, 'N'),
(1, 12, 'N'),
(1, 13, 'N'),
(1, 14, 'N'),
(1, 15, 'N'),
(1, 16, 'N'),
(1, 17, 'N'),
(1, 18, 'N'),
(2, 1, 'N'),
(2, 2, 'N'),
(2, 3, 'N'),
(2, 19, 'N'),
(2, 5, 'N'),
(2, 20, 'N'),
(2, 21, 'N'),
(2, 22, 'N'),
(2, 23, 'N'),
(2, 24, 'N'),
(2, 25, 'N'),
(2, 26, 'N'),
(2, 27, 'N'),
(2, 28, 'N'),
(2, 29, 'N'),
(2, 30, 'N'),
(3, 1, 'N'),
(3, 2, 'N'),
(3, 3, 'N'),
(3, 4, 'N'),
(3, 5, 'N'),
(3, 31, 'N'),
(3, 32, 'N'),
(3, 33, 'N'),
(3, 34, 'N'),
(3, 35, 'N'),
(3, 36, 'N'),
(3, 37, 'N'),
(3, 38, 'N'),
(3, 39, 'N'),
(3, 40, 'N'),
(3, 41, 'N'),
(4, 1, 'N'),
(4, 2, 'N'),
(4, 3, 'N'),
(4, 4, 'N'),
(4, 5, 'N'),
(4, 31, 'N'),
(4, 42, 'N'),
(4, 43, 'N'),
(4, 20, 'N'),
(4, 21, 'N'),
(4, 44, 'N'),
(4, 24, 'N'),
(4, 45, 'N'),
(5, 1, 'N'),
(5, 3, 'N'),
(5, 2, 'N'),
(5, 4, 'N'),
(5, 5, 'N'),
(5, 31, 'N'),
(5, 46, 'N'),
(5, 47, 'N'),
(5, 48, 'N'),
(5, 49, 'N'),
(5, 50, 'N'),
(5, 51, 'N'),
(5, 52, 'N'),
(5, 53, 'N'),
(5, 54, 'N'),
(5, 55, 'N'),
(5, 56, 'N'),
(5, 57, 'N'),
(5, 58, 'N'),
(5, 59, 'N'),
(5, 60, 'N'),
(5, 61, 'N'),
(5, 62, 'N'),
(5, 63, 'N'),
(5, 64, 'N'),
(6, 1, 'N'),
(6, 2, 'N'),
(6, 3, 'N'),
(6, 4, 'N'),
(6, 5, 'N'),
(6, 31, 'N'),
(6, 65, 'N'),
(6, 66, 'N'),
(6, 67, 'N'),
(6, 68, 'N'),
(6, 69, 'N'),
(6, 70, 'N'),
(7, 1, 'N'),
(7, 2, 'N'),
(7, 3, 'N'),
(7, 4, 'N'),
(7, 5, 'N'),
(7, 42, 'N'),
(7, 43, 'N'),
(7, 71, 'N'),
(7, 72, 'N'),
(7, 36, 'N'),
(7, 73, 'N'),
(8, 1, 'N'),
(8, 2, 'N'),
(8, 3, 'N'),
(8, 4, 'N'),
(8, 5, 'N'),
(8, 31, 'N'),
(8, 74, 'N'),
(8, 75, 'N'),
(8, 76, 'N'),
(8, 77, 'N'),
(9, 78, 'N'),
(9, 1, 'N'),
(9, 2, 'N'),
(9, 3, 'N'),
(9, 4, 'N'),
(9, 5, 'N'),
(9, 31, 'N'),
(9, 79, 'N'),
(9, 80, 'N'),
(9, 74, 'N'),
(9, 81, 'N'),
(9, 82, 'N'),
(9, 83, 'N'),
(9, 84, 'N'),
(10, 1, 'N'),
(10, 2, 'N'),
(10, 3, 'N'),
(10, 85, 'N'),
(10, 31, 'N'),
(10, 86, 'N'),
(10, 87, 'N'),
(10, 88, 'N'),
(10, 89, 'N'),
(10, 49, 'N'),
(10, 46, 'N'),
(10, 47, 'N'),
(10, 48, 'N'),
(10, 90, 'N'),
(10, 91, 'N'),
(11, 1, 'N'),
(11, 2, 'N'),
(11, 3, 'N'),
(11, 85, 'N'),
(11, 31, 'N'),
(11, 86, 'N'),
(11, 87, 'N'),
(11, 88, 'N'),
(11, 89, 'N'),
(11, 49, 'N'),
(11, 46, 'N'),
(11, 47, 'N'),
(11, 48, 'N'),
(11, 90, 'N'),
(11, 91, 'N'),
(12, 1, 'N'),
(12, 2, 'N'),
(12, 3, 'N'),
(12, 85, 'N'),
(12, 31, 'N'),
(12, 86, 'N'),
(12, 87, 'N'),
(12, 88, 'N'),
(12, 92, 'N'),
(12, 93, 'N'),
(12, 94, 'N'),
(12, 95, 'N'),
(12, 96, 'N'),
(13, 1, 'N'),
(13, 2, 'N'),
(13, 3, 'N'),
(13, 85, 'N'),
(13, 31, 'N'),
(13, 86, 'N'),
(13, 87, 'N'),
(13, 88, 'N'),
(13, 97, 'N'),
(13, 98, 'N'),
(13, 99, 'N'),
(13, 100, 'N'),
(13, 101, 'N'),
(13, 102, 'N'),
(14, 1, 'N'),
(14, 2, 'N'),
(14, 3, 'N'),
(14, 85, 'N'),
(14, 31, 'N'),
(14, 86, 'N'),
(14, 87, 'N'),
(14, 88, 'N'),
(14, 49, 'N'),
(14, 46, 'N'),
(14, 47, 'N'),
(14, 48, 'N'),
(14, 90, 'N'),
(14, 91, 'N'),
(14, 103, 'N'),
(14, 104, 'N'),
(14, 105, 'N'),
(15, 1, 'N'),
(15, 2, 'N'),
(15, 3, 'N'),
(15, 85, 'N'),
(15, 31, 'N'),
(15, 86, 'N'),
(15, 87, 'N'),
(15, 88, 'N'),
(15, 49, 'N'),
(15, 46, 'N'),
(15, 47, 'N'),
(15, 48, 'N'),
(15, 106, 'N'),
(15, 107, 'N'),
(15, 108, 'N'),
(15, 109, 'N'),
(16, 1, 'N'),
(16, 2, 'N'),
(16, 3, 'N'),
(16, 85, 'N'),
(16, 31, 'N'),
(16, 86, 'N'),
(16, 87, 'N'),
(16, 88, 'N'),
(16, 49, 'N'),
(16, 46, 'N'),
(16, 47, 'N'),
(16, 48, 'N'),
(16, 106, 'N'),
(16, 107, 'N'),
(16, 108, 'N'),
(16, 109, 'N'),
(17, 1, 'N'),
(17, 2, 'N'),
(17, 3, 'N'),
(17, 85, 'N'),
(17, 31, 'N'),
(17, 86, 'N'),
(17, 87, 'N'),
(17, 88, 'N'),
(17, 49, 'N'),
(17, 46, 'N'),
(17, 47, 'N'),
(17, 48, 'N'),
(17, 110, 'N'),
(17, 111, 'N'),
(17, 112, 'N'),
(17, 113, 'N'),
(17, 114, 'N'),
(17, 115, 'N'),
(17, 116, 'N'),
(17, 109, 'N'),
(18, 1, 'N'),
(18, 2, 'N'),
(18, 3, 'N'),
(18, 85, 'N'),
(18, 31, 'N'),
(18, 86, 'N'),
(18, 87, 'N'),
(18, 88, 'N'),
(18, 49, 'N'),
(18, 46, 'N'),
(18, 47, 'N'),
(18, 48, 'N'),
(18, 110, 'N'),
(18, 111, 'N'),
(18, 112, 'N'),
(18, 113, 'N'),
(18, 114, 'N'),
(18, 115, 'N'),
(18, 116, 'N'),
(18, 109, 'N'),
(19, 1, 'N'),
(19, 2, 'N'),
(19, 3, 'N'),
(19, 4, 'N'),
(19, 5, 'N'),
(19, 31, 'N'),
(19, 32, 'N'),
(19, 33, 'N'),
(19, 34, 'N'),
(19, 35, 'N'),
(19, 36, 'N'),
(19, 37, 'N'),
(19, 38, 'N'),
(19, 39, 'N'),
(19, 40, 'N'),
(19, 41, 'N'),
(20, 1, 'N'),
(20, 2, 'N'),
(20, 3, 'N'),
(20, 85, 'N'),
(20, 31, 'N'),
(20, 86, 'N'),
(21, 1, 'N'),
(21, 2, 'N'),
(21, 3, 'N'),
(21, 85, 'N'),
(21, 31, 'N'),
(21, 86, 'N'),
(21, 87, 'N'),
(21, 88, 'N'),
(21, 117, 'N'),
(21, 74, 'N'),
(21, 118, 'N'),
(21, 119, 'N'),
(21, 120, 'N'),
(21, 121, 'N'),
(21, 122, 'N'),
(21, 123, 'N'),
(21, 124, 'N'),
(21, 125, 'N'),
(21, 126, 'N'),
(21, 127, 'N'),
(21, 128, 'N'),
(21, 129, 'N'),
(21, 130, 'N'),
(21, 131, 'N'),
(21, 132, 'N'),
(21, 133, 'N'),
(21, 134, 'N'),
(22, 1, 'N'),
(22, 2, 'N'),
(22, 3, 'N'),
(22, 87, 'N'),
(22, 88, 'N'),
(22, 85, 'N'),
(22, 98, 'N'),
(22, 99, 'N'),
(22, 100, 'N'),
(23, 1, 'N'),
(23, 2, 'N'),
(23, 3, 'N'),
(23, 85, 'N'),
(23, 31, 'N'),
(23, 86, 'N'),
(23, 87, 'N'),
(23, 88, 'N'),
(23, 135, 'N'),
(23, 136, 'N'),
(23, 137, 'N'),
(24, 1, 'N'),
(24, 2, 'N'),
(24, 3, 'N'),
(24, 85, 'N'),
(24, 31, 'N'),
(24, 86, 'N'),
(24, 87, 'N'),
(24, 88, 'N'),
(24, 138, 'N'),
(24, 139, 'N'),
(24, 140, 'N'),
(24, 141, 'N'),
(24, 142, 'N'),
(24, 143, 'N'),
(24, 144, 'N'),
(24, 145, 'N'),
(24, 146, 'N'),
(24, 147, 'N'),
(24, 148, 'N'),
(24, 149, 'N'),
(25, 1, 'N'),
(25, 2, 'N'),
(25, 3, 'N'),
(25, 85, 'N'),
(25, 31, 'N'),
(25, 86, 'N'),
(25, 87, 'N'),
(25, 88, 'N'),
(25, 150, 'N'),
(25, 151, 'N'),
(25, 152, 'N'),
(25, 153, 'N'),
(25, 154, 'N'),
(25, 155, 'N'),
(25, 156, 'N'),
(25, 157, 'N'),
(25, 158, 'N'),
(25, 159, 'N'),
(25, 160, 'N'),
(25, 161, 'N'),
(25, 162, 'N'),
(25, 97, 'N'),
(25, 163, 'N'),
(25, 164, 'N'),
(25, 165, 'N'),
(25, 166, 'N'),
(25, 167, 'N'),
(25, 168, 'N'),
(25, 169, 'N'),
(25, 170, 'N'),
(25, 171, 'N'),
(25, 172, 'N'),
(26, 1, 'N'),
(26, 2, 'N'),
(26, 3, 'N'),
(26, 173, 'N'),
(26, 174, 'N'),
(26, 175, 'N'),
(26, 176, 'N'),
(26, 177, 'N'),
(26, 178, 'N'),
(26, 179, 'N'),
(26, 180, 'N'),
(27, 1, 'N'),
(27, 2, 'N'),
(27, 3, 'N'),
(27, 85, 'N'),
(27, 31, 'N'),
(27, 86, 'N'),
(27, 87, 'N'),
(27, 88, 'N'),
(27, 117, 'N'),
(27, 74, 'N'),
(27, 181, 'N'),
(27, 182, 'N'),
(27, 183, 'N'),
(28, 1, 'N'),
(28, 2, 'N'),
(28, 3, 'N'),
(28, 85, 'N'),
(28, 31, 'N'),
(28, 86, 'N'),
(28, 87, 'N'),
(28, 88, 'N'),
(28, 184, 'N'),
(28, 185, 'N'),
(28, 186, 'N'),
(29, 1, 'N'),
(29, 2, 'N'),
(29, 3, 'N'),
(29, 85, 'N'),
(29, 31, 'N'),
(29, 86, 'N'),
(29, 87, 'N'),
(29, 88, 'N'),
(29, 5, 'N'),
(29, 188, 'N'),
(29, 189, 'N'),
(29, 190, 'N'),
(29, 191, 'N'),
(29, 192, 'N'),
(29, 193, 'N'),
(29, 194, 'N'),
(29, 195, 'N'),
(30, 1, 'N'),
(30, 2, 'N'),
(30, 3, 'N'),
(30, 85, 'N'),
(30, 31, 'N'),
(30, 86, 'N'),
(30, 87, 'N'),
(30, 88, 'N'),
(30, 90, 'N'),
(30, 91, 'N'),
(31, 1, 'N'),
(31, 2, 'N'),
(31, 3, 'N'),
(31, 85, 'N'),
(31, 31, 'N'),
(31, 86, 'N'),
(31, 87, 'N'),
(31, 88, 'N'),
(31, 49, 'N'),
(31, 46, 'N'),
(31, 47, 'N'),
(31, 48, 'N'),
(31, 196, 'N'),
(31, 197, 'N'),
(31, 198, 'N'),
(31, 199, 'N'),
(31, 200, 'N'),
(32, 1, 'N'),
(32, 2, 'N'),
(32, 3, 'N'),
(32, 85, 'N'),
(32, 31, 'N'),
(32, 86, 'N'),
(32, 87, 'N'),
(32, 88, 'N'),
(32, 201, 'N'),
(32, 202, 'N'),
(32, 203, 'N'),
(32, 204, 'N'),
(32, 205, 'N'),
(32, 206, 'N'),
(33, 1, 'N'),
(33, 2, 'N'),
(33, 3, 'N'),
(33, 85, 'N'),
(33, 31, 'N'),
(33, 86, 'N'),
(33, 87, 'N'),
(33, 88, 'N'),
(33, 207, 'N'),
(33, 208, 'N'),
(33, 173, 'N'),
(34, 1, 'N'),
(34, 2, 'N'),
(34, 3, 'N'),
(34, 85, 'N'),
(34, 88, 'N'),
(34, 86, 'N'),
(34, 87, 'N'),
(34, 209, 'N'),
(34, 210, 'N'),
(34, 49, 'N'),
(34, 46, 'N'),
(34, 47, 'N'),
(34, 48, 'N'),
(34, 211, 'N'),
(34, 212, 'N'),
(34, 213, 'N'),
(34, 214, 'N'),
(34, 215, 'N'),
(34, 216, 'N'),
(34, 217, 'N'),
(34, 218, 'N'),
(34, 219, 'N'),
(34, 220, 'N'),
(34, 221, 'N'),
(35, 1, 'N'),
(35, 2, 'N'),
(35, 3, 'N'),
(35, 85, 'N'),
(35, 31, 'N'),
(35, 86, 'N'),
(35, 87, 'N'),
(35, 88, 'N'),
(35, 135, 'N'),
(35, 136, 'N'),
(35, 222, 'N'),
(35, 137, 'N'),
(35, 223, 'N'),
(36, 1, 'N'),
(36, 3, 'N'),
(36, 2, 'N'),
(36, 224, 'N'),
(36, 225, 'N'),
(36, 203, 'N'),
(36, 226, 'N'),
(36, 227, 'N'),
(36, 228, 'N'),
(36, 229, 'N'),
(37, 1, 'N'),
(37, 3, 'N'),
(37, 2, 'N'),
(37, 230, 'N'),
(37, 231, 'N'),
(37, 232, 'N'),
(37, 233, 'N'),
(37, 234, 'N'),
(38, 12, 'N'),
(38, 2, 'N'),
(38, 3, 'N'),
(38, 229, 'N'),
(38, 235, 'N'),
(38, 236, 'N'),
(38, 237, 'N'),
(38, 238, 'N'),
(38, 239, 'N'),
(38, 240, 'N'),
(38, 241, 'N');

-- insert parameters
INSERT INTO parameters (
  name, type, formart, description
) VALUES 
('nr_cnpj_entidade', 'CHAR(14)', '00111222333344', 'Número do CNPJ do Ente Federativo'),
('sg_uf', 'CHAR(2)', 'MG', 'Sigla da Unidade Federativa do Ente Federativo'),
('no_ente', 'VARCHAR(150) CHARACTER SET UNICODE', 'Itabira', 'Nome do Ente Federativo'),
('dt_mes', 'DECIMAL(2,0)', '1', 'Mês da Competência do Demonstrativo'),
('dt_ano', 'DECIMAL(4,0)', '2020', 'Ano da Competência do Demonstrativo'),
('no_segmeto', 'VARCHAR(150) CHARACTER SET UNICODE', 'Renda Fixa', 'Segmento da Aplicação'),
('tp_ativo', 'VARCHAR(150) CHARACTER SET UNICODE', 'FI 100% títulos TN - Art. 7º, I, b', 'Tipo de Ativo'),
('ds_identificacao_ativo', 'VARCHAR(150) CHARACTER SET UNICODE', '11.328.882/0001-35 - BB PREVID. RENDA FIXA IRF-M 1 TP FUNDO DE INVESTIMENTO EM COTAS', 'Identificação do Ativo'),
('nr_apr', 'VARCHAR(8) CHARACTER SET UNICODE', 'A2008038', 'Número da APR'),
('no_fundo_constituido', 'VARCHAR(150) CHARACTER SET UNICODE', 'FUNDO SOLIDÁRIO GARANTIDOR', 'Plano/Fundo Constituido'),
('tp_operacao', 'VARCHAR(150) CHARACTER SET UNICODE', 'Nova Aplicação em Ativo Mantido na Carteira', 'Tipo da Operação'),
('dt_operacao', 'TIMESTAMP(6)', '2020-08-20', 'Data da Operação'),
('dt_liquidacao', 'TIMESTAMP(6)', '2020-08-20', 'Data da Liquidação'),
('vl_quantidade', 'DECIMAL(25,10)', '3574755.226', 'Quantidade de Cotas'),
('vl_ativo', 'DECIMAL(25,10)', '2.79739433', 'Valor do Ativo'),
('vl_quantidade_antes', 'DECIMAL(25,10)', '71438109.63', 'Quantidade de Cotas Antes'),
('vl_operacao', 'DECIMAL(17,2)', '10000000', 'Valor da Operação'),
('vl_quantidade_apos', 'DECIMAL(25,10)', '75012864.85', 'Quantidade de Cotas Depois'),
('dt_mes_bimestre', 'DECIMAL(2,0)', NULL, NULL),
('no_segmento', 'VARCHAR(80) CHARACTER SET UNICODE', 'Renda Fixa', 'Segmento da Aplicação'),
('no_tipo_ativo', 'VARCHAR(60) CHARACTER SET UNICODE', 'FI 100% títulos TN - Art. 7º, I, b', 'Tipo do Ativo da Aplicação'),
('pc_cmn', 'VARCHAR(30) CHARACTER SET UNICODE', NULL, NULL),
('id_ativo', 'VARCHAR(50) CHARACTER SET UNICODE', NULL, NULL),
('no_fundo', 'VARCHAR(8000) CHARACTER SET UNICODE', 'BB PREVIDENCIÁRIO RENDA FIXA FLUXO FUNDO DE. INVESTIMENTO EM COTAS DE FUNDOS DE INVESTIMENTO', 'Razão Social do Fundo de Investimento Analisado'),
('qt_rpps', 'VARCHAR(8001) CHARACTER SET UNICODE', NULL, NULL),
('vl_atual_ativo', 'VARCHAR(8001) CHARACTER SET UNICODE', NULL, NULL),
('vl_total_atual', 'VARCHAR(8001) CHARACTER SET UNICODE', NULL, NULL),
('pc_rpps', 'VARCHAR(8001) CHARACTER SET UNICODE', NULL, NULL),
('vl_patrimonio', 'VARCHAR(8001) CHARACTER SET UNICODE', NULL, NULL),
('pc_patrimonio', 'VARCHAR(8001) CHARACTER SET UNICODE', NULL, NULL),
('dt_envio', 'TIMESTAMP(6)', '2021-03-31 14:15:05', 'Data de Envio do Demonstrativo'),
('no_objeto_contratacao', 'VARCHAR(50) CHARACTER SET UNICODE', 'Consultor de Valores Mobiliarios', 'Forma de Gestão dos Recursos dos RPPS'),
('dt_assinatura_contrato', 'TIMESTAMP(6)', '2018-03-31 14:15:05', 'Data de Assinatura do Contrato'),
('nr_prazo_vigencia', 'CHAR(5) CHARACTER SET UNICODE', '12', 'Prazo de Vigencia (Meses)'),
('vl_mensal_contrato', 'DECIMAL(17,2)', '780.00', 'Valor Contratual Mensal (R$)'),
('nr_processo', 'VARCHAR(100) CHARACTER SET UNICODE', '001/2016', 'Número/ Identificação do Processo Administrativo'),
('no_modalidade_licitacao', 'VARCHAR(50) CHARACTER SET UNICODE', 'Tomada de Precos', 'Modalidade do Procedimetno de Licitação'),
('tp_licitacao', 'VARCHAR(30) CHARACTER SET UNICODE', 'Menor Preco', 'Tipo de Licitação'),
('dt_registro_responsavel', 'TIMESTAMP(6)', '2019-03-31 14:15:05', 'Data de Registro do Responsável Técnico'),
('no_pessoa_representante', 'VARCHAR(150) CHARACTER SET UNICODE', 'Luiz Souza', 'Nome do Representante Legal'),
('no_pessoa_responsavel', 'VARCHAR(150) CHARACTER SET UNICODE', 'José da Silva', 'Nome do Responsável Técnico'),
('nr_cnpj_empresa', 'CHAR(14) CHARACTER SET UNICODE', '30822936000169', 'Número do CNPJ da Instituição Credenciada'),
('no_empresa', 'VARCHAR(150) CHARACTER SET UNICODE', 'Banco do Brasil Gestão de Recursos DTVM S.A', 'Razão Social da Instituição Credenciada'),
('nr_cnpj_fundo', 'CHAR(14) CHARACTER SET UNICODE', '13077415000105', 'Numero do CNPJ do Fundo de Investimento Analisado'),
('dt_analise', 'TIMESTAMP(6)', '2020-02-12 00:00:00', 'Data da Análise do Fundo do Investimento'),
('nr_norma_fundamento', 'VARCHAR(20) CHARACTER SET UNICODE', '8', 'Numero do Fundamento Legal de Criação'),
('dt_norma_fundamento', 'TIMESTAMP(6)', '2012-05-08 14:15:05', 'Data do Fundamento Legal de Criação'),
('te_dispositivo_norma', 'VARCHAR(20) CHARACTER SET UNICODE', 'Art 1', 'Dispositivo do Fundamento Legal de Criação'),
('no_tipo_norma', 'VARCHAR(20) CHARACTER SET UNICODE', 'Lei', 'Tipo do Fundamento Legal de Criação'),
('no_pessoa', 'VARCHAR(150) CHARACTER SET UNICODE', 'José da Silva', 'Nome da Pessoa'),
('no_cargo', 'VARCHAR(50) CHARACTER SET UNICODE', 'Assessor Financeiro', 'Cargo da Pessoa'),
('tp_vinculo', 'VARCHAR(50) CHARACTER SET UNICODE', 'Servidor Efetivo', 'Tipo do Vínculo da Pessoa'),
('no_vinculo_representatividade', 'VARCHAR(50) CHARACTER SET UNICODE', 'Servidor', 'Vinculo/Representatividade da Pessoa'),
('no_orgao_entidade', 'VARCHAR(100) CHARACTER SET UNICODE', 'RPPS', 'Nome do Órgão/Entidade da Pessoa'),
('no_atribuicao', 'VARCHAR(100) CHARACTER SET UNICODE', 'Gestor de Recursos do RPPS', 'Atribuição da Pessoa'),
('no_entidade_governanca', 'VARCHAR(50) CHARACTER SET UNICODE', 'Comitê de Investimentos do RPPS', 'Nome Identificador da Governança'),
('te_ato_inicio_atuacao', 'VARCHAR(50) CHARACTER SET UNICODE', 'Decreto', 'Ato de Início da Atuação da Pessoa'),
('dt_inicio_atuacao', 'TIMESTAMP(6)', '2014-05-08 14:15:05', 'Data de Início de Atuação da Pessoa'),
('te_ato_fim_atuacao', 'VARCHAR(50) CHARACTER SET UNICODE', 'Decreto', 'Ato de Término da Atuação da Pessoa'),
('dt_fim_atuacao', 'TIMESTAMP(6)', '2020-05-08 14:15:05', 'Data de Término de Atuação da Pessoa'),
('no_tipo_certificacao', 'VARCHAR(50)', 'CGRPPS', 'Tipo de Certificado da Pessoa'),
('dt_validade_certificacao', 'TIMESTAMP(6)', '2018-05-08 14:15:05', 'Data de Validade da Certificação da Pessoa'),
('no_entidade_certificadora', 'VARCHAR(5100) CHARACTER SET UNICODE', 'ANBIMA', 'Entidade Certificadora da Certificação Emitida para a Pessoa'),
('nr_cnpj_certificadora', 'CHAR(14) CHARACTER SET UNICODE', '00111222333344', 'Número do CNPJ da Entidade Certificadora'),
('te_finalidade', 'VARCHAR(50) CHARACTER SET UNICODE', 'ENCERRAMENTO_MES', 'Finalidade do DAIR'),
('te_justificativa', 'VARCHAR(2000) CHARACTER SET UNICODE', 'Alteração e inclusão de dados', 'Justificativa de Finalidade do DAIR (Intermediário)'),
('dt_posicao', 'TIMESTAMP(6)', '2021-01-31 00:00:00', 'Data de Posição da Carteira'),
('te_motivo_retificacao', 'VARCHAR(100) CHARACTER SET UNICODE', 'Iniciativa Própria', 'Motivo de Retificação'),
('te_descricao_retificacao', 'VARCHAR(150) CHARACTER SET UNICODE', 'Correção da Data da Certificação', 'Descrição do Motivo da Retificação (Outro)'),
('te_justicativa_retificacao', 'VARCHAR(2000) CHARACTER SET UNICODE', 'Ajuste nas disponibilidades', 'Justificativa da Retificação'),
('tp_instituicao', 'VARCHAR(50) CHARACTER SET UNICODE', NULL, ''),
('ds_descricao', 'VARCHAR(150) CHARACTER SET UNICODE', NULL, ''),
('dt_termo_analise', 'TIMESTAMP(6)', NULL, ''),
('no_orgao', 'VARCHAR(100) CHARACTER SET UNICODE', 'Colegiado Deliberativo do RPPS', 'Nome do Órgão'),
('dt_reuniao', 'TIMESTAMP(6)', '2018-03-31 14:15:05', 'Data da Reunião'),
('te_local_reuniao', 'VARCHAR(100) CHARACTER SET UNICODE', 'Sala do RPPS', 'Local da Reunião'),
('te_principais_liberacoes', 'VARCHAR(2000) CHARACTER SET UNICODE', 'Análise e aprovação do demonstrativo trimestral.', 'Principais Liberações da Reunião'),
('idrubrica', 'INTEGER', NULL, ''),
('no_plano', 'CHAR(20)', NULL, ''),
('nr_cnpj_orgao', 'DECIMAL(14,0)', NULL, ''),
('id_rubrica', 'DECIMAL(4,0)', NULL, ''),
('no_rubrica', 'VARCHAR(50) CHARACTER SET UNICODE', NULL, ''),
('te_rubrica', 'VARCHAR(400) CHARACTER SET UNICODE', NULL, ''),
('vl_rubrica', 'VARCHAR(8001) CHARACTER SET UNICODE', NULL, ''),
('dt_exercicio', 'DECIMAL(4,0)', '2019', 'Exercício do Demonstrativo'),
('te_situacao', 'VARCHAR(80) CHARACTER SET UNICODE', 'Documentos digitalizados enviados', 'Situação do Demonstrativo'),
('tp_plano', 'VARCHAR(30)', 'Previdenciário', 'Tipo de Plano'),
('tp_massa', 'VARCHAR(30)', 'Civil', 'Tipo de Massa'),
('nr_codigo', 'INTEGER', '1003', 'Código Tipo de Norma (tabela interna)'),
('nr_base_calculo', 'DECIMAL(5,0)', '10101', 'Código Base de Cálculo (Tabela Interna)'),
('no_base_calculo', 'VARCHAR(200) CHARACTER SET UNICODE', 'Total das Remunerações de Contribuição dos Servidores Ativos', 'Descrição'),
('cd_comparativo', 'DECIMAL(5,0)', '21001', 'Código Tab. Interna Comparativo'),
('ds_comparativo', 'VARCHAR(70)', 'Contribuição Normal - Ente Federativo', 'Descrição do Comparativo'),
('te_ano_avaliacao_mais_um', 'VARCHAR(100)', '15.45', 'Ano de Avaliação + 1'),
('te_ano_avaliacao_atual', 'VARCHAR(100)', '15.45', 'Ano de Avaliação'),
('te_ano_avaliacao_menos_um', 'VARCHAR(100)', '15.45', 'Ano de Avaliação - 1'),
('dt_exercicio_inicial', 'DECIMAL(4,0)', '2015', 'Exercício Inicial'),
('nr_fluxo', 'DECIMAL(6,0)', '121000', 'Código Tab. Fluxo Atuarial (Tabela Interna)'),
('no_fluxo', 'VARCHAR(120)', 'Benefícios a Conceder - Contribuições do Ente', 'Descrição'),
('vl_projetado', 'VARCHAR(8000) CHARACTER SET UNICODE', '960427', 'Projetada para Ano da Data da Avaliação'),
('vl_executado', 'VARCHAR(8000) CHARACTER SET UNICODE', '945432.18', 'Valor Executado no Ano da Data da Avaliação'),
('vl_diferenca', 'VARCHAR(8000) CHARACTER SET UNICODE', '14994.82', 'Valor da Diferença'),
('tp_beneficiario', 'VARCHAR(20) CHARACTER SET UNICODE', 'Servidores', 'Tipo de Beneficiário'),
('vl_anual_contribuicao', 'VARCHAR(8000) CHARACTER SET UNICODE', '4993815.19', 'Valor Anual da Geração Atual'),
('vl_mensal_contribuicao', 'VARCHAR(8000) CHARACTER SET UNICODE', '356336.6', 'Valor Mensal Estatística da População Coberta'),
('cd_plano_beneficio', 'DECIMAL(6,0)', '110101', 'Código Plano de Benefícios (Tabela Interna)'),
('no_beneficio', 'VARCHAR(200)', 'Aposentadoria Por Invalidez Permanente', 'Benefícios'),
('vl_custo_anual_previsto', 'VARCHAR(8000) CHARACTER SET UNICODE', '399086.25', 'Valor Custo Anual Previsto'),
('pc_contribuicao', 'DECIMAL(15,2)', '2.47', '% Sobre Base de Contribuição'),
('cd_custo_normal_reparticao', 'DECIMAL(6,0)', '110102', 'Código Plano de Benefícios'),
('no_reparticao', 'VARCHAR(200)', 'Pensão Por Morte de Aposentado por Invalidez', 'Benefícios'),
('vl_pago_dois_anos_antes', 'VARCHAR(8000) CHARACTER SET UNICODE', '0.01', 'Valor Pago Dois Anos Antes do Ano da Avaliação'),
('vl_pago_um_ano_antes', 'VARCHAR(8000) CHARACTER SET UNICODE', '1059.7', 'Valor Pago Um Ano Antes do Ano da Avaliação'),
('vl_pago_ano_atual', 'VARCHAR(8000) CHARACTER SET UNICODE', '943.2', 'Valor Pago Ano da Avaliação'),
('vl_minimo_um_ano_apos', 'VARCHAR(8000) CHARACTER SET UNICODE', '0.00', 'Valor Mínimo Próximo Ano do Ano da Avaliação'),
('vl_previsto_um_ano_apos', 'VARCHAR(8000) CHARACTER SET UNICODE', '70921.26', 'Valor Previsto Próximo Ano do Ano da Avaliação'),
('cnpj_orgao', 'CHAR(14)', '11806792000102', 'CNPJ Órgão/Entidade'),
('cd_populacao', 'DECIMAL(7,0)', '3430200', 'Código População Coberta'),
('tp_populacao', 'VARCHAR(20)', 'Aposentados', 'População Coberta - Descrição Nível 1'),
('no_cat_populacao', 'VARCHAR(100)', 'DEMAIS SERVIDORES', 'População Coberta - Descrição Nível 2'),
('no_regra_enquadramento', 'VARCHAR(100)', 'Compulsória', 'População Coberta - Descrição Nível 3'),
('no_criterio_aposentadoria', 'VARCHAR(100)', 'null', 'População Coberta - Descrição Nível 4'),
('qt_grupo_masc', 'DECIMAL(10,0)', '1', 'Quantidade Masculino'),
('vl_medio_base_calculo_masc', 'DECIMAL(15,2)', '1018.33', 'Média Base Cálculo / Benefício Masculino'),
('vl_idade_media_masc', 'DECIMAL(5,2)', '77', 'Idade Média Masculino'),
('vl_idade_med_aposent_masc', 'DECIMAL(5,2)', '70', 'Idade Média Aposentadoria Projetada Masculino'),
('vl_idade_med_adm_masc', 'DECIMAL(5,2)', '43', 'Idade Média Admissão Masculino'),
('vl_folha_mensal_masc', 'DECIMAL(15,2)', '1018.33', 'Valor Folha Mensal Masculino'),
('qt_grupo_fem', 'DECIMAL(10,0)', '3', 'Quantidade Feminino'),
('vl_medio_base_calculo_fem', 'DECIMAL(15,2)', '1034.2', 'Média Base Cálculo / Benefício Feminino'),
('vl_idade_media_fem', 'DECIMAL(5,2)', '52', 'Idade Média Feminino'),
('vl_idade_med_aposent_fem', 'DECIMAL(5,2)', '48', 'Idade Média Aposentadoria Projetada Feminino'),
('vl_idade_med_adm_fem', 'DECIMAL(5,2)', '34', 'Idade Média Admissão Feminino'),
('vl_folha_mensal_fem', 'DECIMAL(15,2)', '3102.6', 'Valor Folha Mensal Feminino'),
('cd_demonstrativo', 'DECIMAL(6,0)', '500000', 'Código Dem. Result. Atuarial'),
('ds_item_resultado', 'VARCHAR(200)', 'ATIVOS GARANTIDORES DOS COMPROMISSOS DO PLANO DE BENEFÍCIOS', 'Descrição Dem. Result. Atuarial'),
('vl_geracao_atual', 'VARCHAR(8000) CHARACTER SET UNICODE', '207554161.7', 'Valor da Geração Atual'),
('cd_hipotese_demografica', 'DECIMAL(5,0)', '10001', 'Codigo Hipoteses Dem. Econ. (tabela interna)'),
('ds_hipotese_demografica', 'VARCHAR(150) CHARACTER SET UNICODE', 'Projeção da Taxa de Juros Real para o Exercício', 'Descricao Hipoteses Dem. Econ.'),
('tp_unidade', 'VARCHAR(20) CHARACTER SET UNICODE', 'Percentual', 'Unidade'),
('te_hipotese_demografica', 'VARCHAR(1000) CHARACTER SET UNICODE', '6', 'Hipoteses'),
('vl_previsto_dois_antes', 'VARCHAR(250)', '0', 'Valor Previsto no DRAA de "Ano da Data da Avaliacao -2'),
('vl_ocorrido_dois_antes', 'VARCHAR(250)', '0', 'Valor Ocorrido em "Ano da Data da Avaliacao - 2'),
('vl_previsto_um_antes', 'VARCHAR(250)', '0', 'Valor Previsto no DRAA de "Ano da Data da Avaliacao -1'),
('vl_ocorrido_um_antes', 'VARCHAR(250)', '0', 'Valor Ocorrido em "Ano da Data da Avaliacao - 1'),
('vl_previsto_ano_avaliacao', 'VARCHAR(250)', '6', 'Valor Previsto no DRAA de "Ano da Data da Avaliacao'),
('vl_ocorrido_ano_avaliacao', 'VARCHAR(250)', '0', 'Valor Ocorrido em "Ano da Data da Avaliacao'),
('vl_perspectiva_longo_prazo', 'VARCHAR(250)', '6', 'Perspectiva Longo Prazo'),
('te_justificativa_tecnica', 'VARCHAR(500) CHARACTER SET UNICODE', 'NÃO TEMOS A INFORMACAO', 'Justificativa Técnica'),
('cd_hipotese_biometrica_masc', 'DECIMAL(4,0)', '1211', 'Codigo Hipoteses Biometricas (tabela interna) - Masculina'),
('ds_hipotese_biometrica_masc', 'VARCHAR(100) CHARACTER SET UNICODE', 'IBGE 2016 - Ambos - Extrap MPS', 'Descricao da Tabua - Populacao Masculina'),
('cd_tipo_tabua_masc', 'DECIMAL(4,0)', '1000', 'Codigo Hipoteses Biometricas (tabela interna) - Masculina'),
('tp_tabua_masc', 'VARCHAR(100) CHARACTER SET UNICODE', 'Tábua de Mortalidade de Válido - Fase Laborativa', 'Tipo de Tabua - Masculina'),
('nr_even_prev_menos_dois_anos_m', 'DECIMAL(15,2)', '4.48', 'Numero de Eventos Previstos pela Tabua Utilizada no DRAA de "ANO DA DATA DA AVALIACAO -2" - Masculina'),
('nr_even_ocor_menos_dois_anos_m', 'DECIMAL(15,2)', '0', 'Numero de Eventos Ocorridos em "ANO DA DATA DA AVALIACAO -2" - Masculina'),
('nr_even_prev_menos_um_ano_m', 'DECIMAL(15,2)', '4.37', 'Numero de Eventos Previstos pela Tabua Utilizada no DRAA de "ANO DA DATA DA AVALIACAO -1" - Masculina'),
('nr_even_ocor_menos_um_ano_m', 'DECIMAL(15,2)', '0', 'Numero de Eventos Ocorridos em "ANO DA DATA DA AVALIAÇÂO -1" - Masculina'),
('nr_even_prev_menos_ano_aval_m', 'DECIMAL(15,2)', '4.43', 'Numero de Eventos Previstos pela Tabua Utilizada no DRAA de "ANO DA DATA DA AVALIACAO" - Masculina'),
('nr_even_ocor_menos_ano_aval_f', 'DECIMAL(15,2)', null, 'Numero de Eventos Ocorridos em "ANO DA DATA DA AVALIACAO" - Feminina'),
('ds_justificativa_tecnica_fem', 'VARCHAR(500) CHARACTER SET UNICODE', null, 'Justificativa Tecnica para Eventuais Discrepancias - Feminina'),
('nr_notificacao', 'VARCHAR(14)', null, 'Número da Notificação'),
('no_tipo_documento', 'VARCHAR(50)', null, 'DRAA Tipo de Documento'),
('no_item_analise', 'VARCHAR(100)', null, 'Consistência - Segregação da Massa Item de Análise'),
('no_situacao_item_analise', 'VARCHAR(100)', null, 'Notificacao sem resposta. Prazo expirado. Situacao irregular Situação do Item de Análise'),
('dt_notificao', 'TIMESTAMP(6)', null, '2018-06-14 10:37:21 Data da Notificação'),
('dt_preclusao', 'TIMESTAMP(6)', null, '2018-07-16 00:00:00 Data da Preclusão'),
('dt_resposta', 'TIMESTAMP(6)', null, '2018-07-16 00:00:00 Data da Resposta'),
('nr_prazo_resposta', 'INTEGER', null, '30 Prazo para Resposta (Dias)'),
('dt_competencia_base_cadastral', 'CHAR(14)', null, '2006-01-01 00:00:00 Competência da Base Cadastral'),
('tp_poder', 'VARCHAR(50)', null, 'Legislativo Poder do Órgão'),
('tp_orgao', 'VARCHAR(50)', null, 'Administração Direta Tipo do Órgão'),
('cd_tema', 'DECIMAL(5,0)', null, '31001 Codigo Interno Parecer Atuarial'),
('no_tema', 'VARCHAR(160) CHARACTER SET UNICODE', null, 'Perspectivas de alteração futura no perfil e na composição da massa de segurados Tema'),
('te_parecer', 'VARCHAR(1000) CHARACTER SET UNICODE', null, 'null Parecer'),
('tx_juros', 'DECIMAL(3,0)', null, '6 Taxa de Juros'),
('vl_aporte', 'VARCHAR(8000) CHARACTER SET UNICODE', null, '11286673.04 Valor do Aporte'),
('vl_aliquotas', 'VARCHAR(8000) CHARACTER SET UNICODE', null, '63.77 Valor da Alíquota'),
('vl_base_calculo', 'VARCHAR(8000) CHARACTER SET UNICODE', null, '1154494503 Valor da Base de Cálculo'),
('vl_saldo_inicial', 'VARCHAR(8000) CHARACTER SET UNICODE', null, '9551894742 Valor do Saldo Inicial'),
('vl_pagamentos', 'VARCHAR(8000) CHARACTER SET UNICODE', null, '-736221144.7 Valor de Pagamentos'),
('vl_saldo_final', 'VARCHAR(8000) CHARACTER SET UNICODE', null, '9388787282 Saldo Final'),
('vl_juros', 'VARCHAR(8000) CHARACTER SET UNICODE', null, '18700561.95 Valor do Juros'),
('vl_amortizacao', 'VARCHAR(8000) CHARACTER SET UNICODE', null, '-238588921.9 Valor de Amortização'),
('nr_plano_benefico', 'DECIMAL(6,0)', null, '110102 Codigo Interno do Plano de Beneficios'),
('no_beneficio_plano', 'VARCHAR(100) CHARACTER SET UNICODE', null, 'Aposentadorias Programadas (Por Idade, Tempo de Contribuição e Compulsória) Benefício do Plano'),
('nr_regime_financeiro', 'DECIMAL(3,0)', null, '104 Código Regimes e Métodos'),
('ds_regime_financeiro', 'VARCHAR(80) CHARACTER SET UNICODE', null, 'REGIME FINANCEIRO DE CAPITALIZAÇÃO - AGREGADO Regime Financeiro e Método de Financiamento'),
('ds_metodo_financiamento', 'VARCHAR(500) CHARACTER SET UNICODE', null, 'null Descrição do Método de Financiamento'),
('tp_contribuicao', 'VARCHAR(50)', null, 'Ente Federativo Tipo de Contribuição Normal'),
('vl_anual_base_calculo', 'VARCHAR(8000) CHARACTER SET UNICODE', null, '1055600301 Valor Anual Base Cálculo'),
('vl_aliquota', 'VARCHAR(8000) CHARACTER SET UNICODE', null, '12.2 Alíquota'),
('vl_contribuicao_esperada', 'VARCHAR(8000) CHARACTER SET UNICODE', null, '128783236.8 Contribuição Esperada Atual'),
('vl_aliquota_definida', 'VARCHAR(8000) CHARACTER SET UNICODE', null, '12.2 Alíquota Definida na Avaliacao Atuarial'),
('vl_contribuicao_definida', 'VARCHAR(8000) CHARACTER SET UNICODE', null, '128783236.8 Contribuição Esperada Definida'),
('in_retificacao', 'CHAR(5)', null, 'Sim Retificação'),
('in_motivo_notificacao', 'CHAR(5)', null, 'Sim Motivado por Notificacao'),
('no_previdencia_complementar', 'CHAR(5)', null, 'Não Implataou Previdencia Complementar'),
('no_beneficio_tesouro', 'CHAR(5)', null, 'Sim Beneficios Mantidos pelo Tesouro'),
('no_segregacao_massa', 'VARCHAR(50) CHARACTER SET UNICODE', null, 'Instituida neste Exercicio ou Mantida Nome da Segregação em Massa'),
('dt_ingresso_segurado', 'VARCHAR(15)', null, '2020-03-01 00:00:00 Data de Ingresso do Segurado'),
('nr_idade_segurado', 'CHAR(5)', null, '20 Idade do Segurado'),
('in_segurado_servidor', 'CHAR(5)', null, 'Sim Condicao Segurado - Servidor'),
('in_segurado_aposentado', 'CHAR(5)', null, 'Sim Condicao Segurado - Aposentado'),
('in_segurado_pensionista', 'CHAR(5)', null, 'Sim Condicao Segurado - Pensionista'),
('no_atuario_responsavel', 'VARCHAR(100)', null, 'José da Silva Nome do Atuario Responsavel'),
('nr_registro_prof_atuario', 'VARCHAR(30)', null, '123 Numero do Registro Profissional'),
('tp_documento', 'VARCHAR(40)', null, 'Lei Tipo de Documento'),
('nr_documento', 'VARCHAR(20)', null, '7114 Numero do Documento'),
('dt_documento', 'VARCHAR(15)', null, '2009-12-23 00:00:00 Data do Documento'),
('no_categoria_demonstrativo', 'VARCHAR(15)', null, 'Detalhe Tipo de Categoria'),
('vl_geracao_futura', 'VARCHAR(8000) CHARACTER SET UNICODE', null, '0 Valor da Geracao Futura'),
('ds_plano_segregacao', 'VARCHAR(30) CHARACTER SET UNICODE', null, 'Previdenciário Nome do Plano de Segregação'),
('no_sujeito_passivo', 'VARCHAR(30) CHARACTER SET UNICODE', null, 'Ente Nome do Sujeito Passivo(Ente, Servidor, Aposentado, Pensionista, Custo Suplementar)'),
('dt_inicio_vigencia', 'TIMESTAMP(6)', null, '2021-03-31 14:15:05 Data de Iníco de Vigência da Alíquota'),
('dt_fim_vigencia', 'TIMESTAMP(6)', null, '2021-03-31 14:15:05 Data de Fim de Vigência da Alíquota'),
('id_vigente', 'VARCHAR(15) CHARACTER SET UNICODE', null, 'Vigente Identifica se a Alíquota está Vigente ou não'),
('tp_regime', 'VARCHAR(15) CHARACTER SET UNICODE', null, 'RPPS Tipo de Regime'),
('nr_crp', 'VARCHAR(20) CHARACTER SET UNICODE', null, '931001-190583 Número de Emissão do CRP'),
('ds_situacao', 'VARCHAR(20) CHARACTER SET UNICODE', null, 'Vigente Situação do CRP (Vigente ou Vencido)'),
('dt_emissao', 'VARCHAR(20) CHARACTER SET UNICODE', null, '2021-03-31 14:15:05 Data de Emissão do CRP'),
('dt_validade', 'VARCHAR(20) CHARACTER SET UNICODE', null, '2021-03-31 14:15:05 Data de Vencimento do CRP'),
('tp_crp', '"tp_crp VARCHAR(20) CHARACTER SET UNICODE"', null, 'Judicial Tipo de Emissão do CRP (Administrativo ou Judicial)'),
('dt_inicio', 'TIMESTAMP(6)', null, '2021-03-31 14:15:05 Data de Criação do Regime Previdenciário'),
('dt_fim', 'TIMESTAMP(6)', null, '2021-03-31 14:15:05 Data de Extinção do Regime Previdenciário'),
('no_tipo_legislacao', 'VARCHAR(50) CHARACTER SET UNICODE', null, 'Lei Tipo de Documento (Decreto, Lei, etc)'),
('nr_legislacao', 'VARCHAR(400) CHARACTER SET UNICODE', null, '700 Numero do Documento'),
('dt_legislacao', 'TIMESTAMP(6)', null, '2021-03-31 14:15:05 Data de Criação da Legislação'),
('te_ementa', 'VARCHAR(8000) CHARACTER SET UNICODE', null, 'Criação do RPPS Ementa da Legislação'),
('tp_vinculo_legislacao', 'VARCHAR(30) CHARACTER SET UNICODE', null, 'Criação do Regime Tipo de Vínculo da Legislação');

-- insert tabela api_responses
INSERT INTO api_responses (id, description, metadata, data_dictionary, response_example) VALUES (1, 'Seleciona registro da tabela / DAIR_APLICACOES_RESGATE', '{"queueDuration": null, "queryDuration": null, "results": [{"resultSet": null, "data": [{"nr_cnpj_entidade": null, "sg_uf": null, "no_ente": null, "dt_mes": null, "dt_ano": null, "no_segmeto": null, "tp_ativo": null, "ds_identificacao_ativo": null, "nr_apr": null, "no_fundo_constituido": null, "tp_operacao": null, "dt_operacao": null, "dt_liquidacao": null, "vl_quantidade": null, "vl_ativo": null, "vl_quantidade_antes": null, "vl_operacao": null, "vl_quantidade_apos": null}]}]}', null, '{"results": [{"data": [{"sg_uf": null, "dt_ano": null, "dt_mes": null, "nr_apr": null, "no_ente": null, "tp_ativo": null, "vl_ativo": null, "no_segmeto": null, "dt_operacao": null, "tp_operacao": null, "vl_operacao": null, "dt_liquidacao": null, "vl_quantidade": null, "nr_cnpj_entidade": null, "vl_quantidade_apos": null, "vl_quantidade_antes": null, "no_fundo_constituido": null, "ds_identificacao_ativo": null}], "resultSet": null}], "queryDuration": null, "queueDuration": null}');
INSERT INTO api_responses (id, description, metadata, data_dictionary, response_example) VALUES (2, 'Seleciona registro da tabela /DAIR_CARTEIRA', '{"queueDuration": 25, "queryDuration": 4163, "results": [{"resultSet": true, "data": [{"nr_cnpj_entidade": "45298569000113", "sg_uf": "SP", "no_ente": "Altinópolis", "dt_mes_bimestre": 2, "dt_ano": 2017, "no_segmento": "Renda Fixa", "no_tipo_ativo": "FI de Renda Fixa", "pc_cmn": "30", "id_ativo": "13077418000149", "no_fundo": "BB PERFIL FIC RENDA FIXA PREVIDENCIÁRIO", "qt_rpps": "2846876.2833257630", "vl_atual_ativo": "1.8523831730", "vl_total_atual": "5273505.72", "pc_rpps": "10.54", "vl_patrimonio": "4816396409.15", "pc_patrimonio": "0.11"}]}]}', null, '{"results": [{"data": [{"sg_uf": "SP", "dt_ano": 2017, "pc_cmn": "30", "no_ente": "Altinópolis", "pc_rpps": "10.54", "qt_rpps": "2846876.2833257630", "id_ativo": "13077418000149", "no_fundo": "BB PERFIL FIC RENDA FIXA PREVIDENCIÁRIO", "no_segmento": "Renda Fixa", "no_tipo_ativo": "FI de Renda Fixa", "pc_patrimonio": "0.11", "vl_patrimonio": "4816396409.15", "vl_atual_ativo": "1.8523831730", "vl_total_atual": "5273505.72", "dt_mes_bimestre": 2, "nr_cnpj_entidade": "45298569000113"}], "resultSet": true}], "queryDuration": 4163, "queueDuration": 25}');
INSERT INTO api_responses (id, description, metadata, data_dictionary, response_example) VALUES (3, 'Seleciona registro da tabela /DAIR_FORMA_GESTAO', '{"queueDuration": null, "queryDuration": null, "results": [{"resultSet": null, "data": [{"nr_cnpj_entidade": null, "sg_uf": null, "no_ente": null, "dt_mes": null, "dt_ano": null, "dt_envio": null, "no_objeto_contratacao": null, "dt_assinatura_contrato": null, "nr_prazo_vigencia": null, "vl_mensal_contrato": null, "nr_processo": null, "no_modalidade_licitacao": null, "tp_licitacao": null, "dt_registro_responsavel": null, "no_pessoa_representante": null, "no_pessoa_responsavel": null}]}]}', null, '{"results": [{"data": [{"sg_uf": "GO", "dt_ano": 2018, "dt_mes": 1, "no_ente": "Indiara", "dt_envio": "2018-02-22 21:32:52.980", "nr_processo": "216/2017", "tp_licitacao": "Menor Preco", "nr_cnpj_entidade": "00005959000110", "nr_prazo_vigencia": "9", "vl_mensal_contrato": 2200, "no_objeto_contratacao": "Outros", "no_pessoa_responsavel": null, "dt_assinatura_contrato": "2017-04-05 03:00:00.000", "dt_registro_responsavel": "2016-01-18 02:00:00.000", "no_modalidade_licitacao": "Convite", "no_pessoa_representante": null}], "resultSet": true}], "queryDuration": 472, "queueDuration": 17293}');
INSERT INTO api_responses (id, description, metadata, data_dictionary, response_example) VALUES (4, 'Seleciona registro da tabela /DAIR_FUNDO_INVEST_ANALISADOS', '{"queueDuration": null, "queryDuration": null, "results": [{"resultSet": null, "data": [{"nr_cnpj_entidade": null, "sg_uf": null, "no_ente": null, "dt_mes": null, "dt_ano": null, "dt_envio": null, "nr_cnpj_empresa": null, "no_empresa": null, "no_segmento": null, "no_tipo_ativo": null, "nr_cnpj_fundo": null, "no_fundo": null, "dt_analise": null}]}]}', null, '{"results": [{"data": [{"sg_uf": "GO", "dt_ano": 2022, "dt_mes": 8, "no_ente": "Maurilândia", "dt_envio": "2022-11-07 13:12:05.283", "no_fundo": "BB PREVIDENCIARIO RENDA FIXA REFERENCIADO DI LONGO PRAZO PERFIL FUNDO DE INVESTIMENTO EM COTAS DE FUNDOS DE INVESTIMENTO", "dt_analise": "2022-03-09 03:00:00.000", "no_empresa": "BB GESTÃO DE RECURSOS DISTRIBUIDORA DE TÍTULOS E VALORES IMOBILIÁRIOS S.A", "no_segmento": "Renda Fixa", "no_tipo_ativo": "Fundos de Investimento em Renda Fixa - Geral - Art. 7º, III, a", "nr_cnpj_fundo": "13077418000149", "nr_cnpj_empresa": "30822936000169", "nr_cnpj_entidade": "02056752000108"}], "resultSet": true}], "queryDuration": 321, "queueDuration": 1}');
INSERT INTO api_responses (id, description, metadata, data_dictionary, response_example) VALUES (5, 'Seleciona registro da tabela /DAIR_GOVERNANCA', '{"queueDuration": null, "queryDuration": null, "results": [{"resultSet": null, "data": [{"nr_cnpj_entidade": null, "no_ente": null, "sg_uf": null, "dt_mes": null, "dt_ano": null, "dt_envio": null, "nr_norma_fundamento": null, "dt_norma_fundamento": null, "te_dispositivo_norma": null, "no_tipo_norma": null, "no_pessoa": null, "no_cargo": null, "tp_vinculo": null, "no_vinculo_representatividade": null, "no_orgao_entidade": null, "no_atribuicao": null, "no_entidade_governanca": null, "te_ato_inicio_atuacao": null, "dt_inicio_atuacao": null, "te_ato_fim_atuacao": null, "dt_fim_atuacao": null, "no_tipo_certificacao": null, "dt_validade_certificacao": null, "no_entidade_certificadora": null, "nr_cnpj_certificadora": null}]}]}', null, '{"results": [{"data": [{"sg_uf": "GO", "dt_ano": 2023, "dt_mes": 1, "no_ente": "Novo Brasil", "dt_envio": "2023-02-24 16:50:14.360", "no_cargo": null, "no_pessoa": "SELMA CARLOS FILHO GONCALVES", "tp_vinculo": "SERVIDOR EFETIVO", "no_atribuicao": "OUTROS", "no_tipo_norma": "Lei", "dt_fim_atuacao": null, "nr_cnpj_entidade": "00006874000156", "dt_inicio_atuacao": "2022-11-30 03:00:00.000", "no_orgao_entidade": "", "te_ato_fim_atuacao": null, "dt_norma_fundamento": "2007-02-28 03:00:00.000", "nr_norma_fundamento": "112", "no_tipo_certificacao": "CGRPPS", "te_dispositivo_norma": "Art. 71, § 2º", "nr_cnpj_certificadora": null, "te_ato_inicio_atuacao": "Portaria", "no_entidade_governanca": "COMITÊ DE INVESTIMENTOS DO RPPS", "dt_validade_certificacao": "2026-03-25 03:00:00.000", "no_entidade_certificadora": "Outros", "no_vinculo_representatividade": null}], "resultSet": true}], "queryDuration": 930, "queueDuration": 21}');
INSERT INTO api_responses (id, description, metadata, data_dictionary, response_example) VALUES (6, 'Seleciona registro da tabela /DAIR_IDENTIFICACAO', '{"queueDuration": null, "queryDuration": null, "results": [{"resultSet": null, "data": [{"nr_cnpj_entidade": null, "sg_uf": null, "no_ente": null, "dt_mes": null, "dt_ano": null, "dt_envio": null, "te_finalidade": null, "te_justificativa": null, "dt_posicao": null, "te_motivo_retificacao": null, "te_descricao_retificacao": null, "te_justicativa_retificacao": null}]}]}', null, '{"results": [{"data": [{"sg_uf": "SP", "dt_ano": 2021, "dt_mes": 8, "no_ente": "Cândido Rodrigues", "dt_envio": "2023-01-26 14:08:05.857", "dt_posicao": "2021-08-31 03:00:00.000", "te_finalidade": "ENCERRAMENTO_MES", "nr_cnpj_entidade": "45374261000100", "te_justificativa": null, "te_motivo_retificacao": null, "te_descricao_retificacao": null, "te_justicativa_retificacao": null}], "resultSet": true}], "queryDuration": 206, "queueDuration": 0}');
INSERT INTO api_responses (id, description, metadata, data_dictionary, response_example) VALUES (7, 'Seleciona registro da tabela /DAIR_INSTITUICAO_CREDENCIADA', '{"queueDuration": null, "queryDuration": null, "results": [{"resultSet": null, "data": [{"nr_cnpj_entidade": null, "sg_uf": null, "no_ente": null, "dt_mes": null, "dt_ano": null, "nr_cnpj_empresa": null, "no_empresa": null, "tp_instituicao": null, "ds_descricao": null, "nr_processo": null, "dt_termo_analise": null}]}]}', null, '{"results": [{"data": [{"sg_uf": "PR", "dt_ano": 2022, "dt_mes": 4, "no_ente": "Maringá", "no_empresa": "NAVI CAPITAL - ADMINISTRADORA E GESTORA DE RECURSOS FINANCEIROS LTDA", "nr_processo": "84/2019", "ds_descricao": null, "tp_instituicao": "Gestor do Fundo de Investimento", "nr_cnpj_empresa": "27133825000130", "dt_termo_analise": "2019-02-11 02:00:00.000", "nr_cnpj_entidade": "76282656000106"}], "resultSet": true}], "queryDuration": 1399, "queueDuration": 1}');
INSERT INTO api_responses (id, description, metadata, data_dictionary, response_example) VALUES (8, 'Seleciona registro da tabela /DAIR_REGIME_ATA', '{"queueDuration": null, "queryDuration": null, "results": [{"resultSet": null, "data": [{"nr_cnpj_entidade": null, "sg_uf": null, "no_ente": null, "dt_mes": null, "dt_ano": null, "dt_envio": null, "no_orgao": null, "dt_reuniao": null, "te_local_reuniao": null, "te_principais_liberacoes": null}]}]}', null, '{"results": [{"data": [{"sg_uf": "GO", "dt_ano": 2017, "dt_mes": 1, "no_ente": "Novo Brasil", "dt_envio": "2017-10-05 11:59:23.947", "no_orgao": "Colegiado Deliberativo do RPPS", "dt_reuniao": "2017-05-03 03:00:00.000", "nr_cnpj_entidade": "00006874000156", "te_local_reuniao": "BRASIL - PREV", "te_principais_liberacoes": "APROVAÇÃO DA POLÍTICA ANUAL DE INVESTIMENTOS - PAI."}], "resultSet": true}], "queryDuration": 494, "queueDuration": 213}');
INSERT INTO api_responses (id, description, metadata, data_dictionary, response_example) VALUES (9, 'Seleciona registro da tabela /DIPR', '{"queueDuration": 190, "queryDuration": 1797}', null, '{"results": [{"data": [{"sg_uf": "MG", "dt_ano": 2020, "dt_mes": 10, "no_ente": "Felixlândia", "dt_envio": "2020-11-25 14:32:34.503", "no_orgao": "MUNICIPIO DE FELIXLANDIA", "no_plano": "PREVIDENCIARIO", "idrubrica": 1, "id_rubrica": 64, "no_rubrica": "SEG", "te_rubrica": "Dos servidores", "vl_rubrica": "88882.18", "nr_cnpj_orgao": 17695032000151, "nr_cnpj_entidade": "17695032000151"}], "resultSet": true}], "queryDuration": 1797, "queueDuration": 190}');
INSERT INTO api_responses (id, description, metadata, data_dictionary, response_example) VALUES (10, 'Seleciona registro da tabela /DRAA_BASE_CALCULO_AMORTIZACAO', '{"queueDuration": 1, "queryDuration": 247}', null, '{"results": [{"data": [{"sg_uf": "SP", "no_ente": "Cândido Rodrigues", "dt_envio": "2020-09-04 19:57:44.633", "tp_massa": "Civil", "tp_plano": "Previdenciário", "nr_codigo": 1004, "te_situacao": "Documentos Digitalizados", "dt_exercicio": 2020, "no_tipo_norma": "Decreto", "no_base_calculo": "Total das Remunerações de Contribuição dos Servidores Ativos", "nr_base_calculo": 10101, "nr_cnpj_entidade": "45374261000100", "dt_norma_fundamento": "2020-01-07 03:00:00.000", "nr_norma_fundamento": "2088", "te_dispositivo_norma": "Art. 1"}], "resultSet": true}], "queryDuration": 247, "queueDuration": 1}');
INSERT INTO api_responses (id, description, metadata, data_dictionary, response_example) VALUES (11, 'Seleciona registro da tabela /DRAA_BASE_CALCULO_ENTE', '{"queueDuration": 1, "queryDuration": 224}', null, '{"results": [{"data": [{"sg_uf": "AL", "no_ente": "Poço das Trincheiras", "dt_envio": "2023-04-10 14:07:02.377", "tp_massa": "Civil", "tp_plano": "Previdenciário", "nr_codigo": 1002, "te_situacao": "Documentos Digitalizados", "dt_exercicio": 2023, "no_tipo_norma": "Lei", "no_base_calculo": "Total das Remunerações de Contribuição dos Servidores Ativos", "nr_base_calculo": 10101, "nr_cnpj_entidade": "12259040000131", "dt_norma_fundamento": "2021-01-13 03:00:00.000", "nr_norma_fundamento": "331", "te_dispositivo_norma": "ART. 17 - III"}], "resultSet": true}], "queryDuration": 224, "queueDuration": 1}');
INSERT INTO api_responses (id, description, metadata, data_dictionary, response_example) VALUES (12, 'Seleciona registro da tabela /DRAA_COMPARATIVO_AVALIACAO', '{"queueDuration": 1, "queryDuration": 418}', null, '{"results": [{"data": [{"sg_uf": "MT", "no_ente": "Santo Antônio do Leverger", "dt_envio": "2016-10-07 13:15:27.500", "tp_massa": "Civil", "tp_plano": "Previdenciário", "te_situacao": "Substituída Antes da Recepção dos Arquivos Digitalizados", "dt_exercicio": 2015, "cd_comparativo": 31006, "ds_comparativo": "Média do Valor do Benefícios dos Pensionistas", "nr_cnpj_entidade": "03507555000112", "te_ano_avaliacao_atual": "748.17", "te_ano_avaliacao_mais_um": "815.47", "te_ano_avaliacao_menos_um": "678.98"}], "resultSet": true}], "queryDuration": 418, "queueDuration": 1}');
INSERT INTO api_responses (id, description, metadata, data_dictionary, response_example) VALUES (13, 'Seleciona registro da tabela /DRAA_COMPARATIVO_RECEITA', '{"queueDuration": 0, "queryDuration": 630}', null, '{"results": [{"data": [{"sg_uf": "RJ", "no_ente": "Governo do Estado do Rio de Janeiro", "dt_envio": "2018-04-26 16:54:56.713", "no_fluxo": "Benefícios Concedidos - Encargos - Aposentadorias por Invalidez", "nr_fluxo": 214001, "tp_massa": "Civil", "tp_plano": "Financeiro", "te_situacao": "Documentos Digitalizados", "dt_exercicio": 2018, "vl_diferenca": ".01", "vl_executado": ".01", "vl_projetado": ".02", "nr_cnpj_entidade": "42498600000171", "dt_exercicio_inicial": 2015}], "resultSet": true}], "queryDuration": 630, "queueDuration": 0}');
INSERT INTO api_responses (id, description, metadata, data_dictionary, response_example) VALUES (14, 'Seleciona registro da tabela /DRAA_CONTRIBUICAO', '{"queueDuration": 5, "queryDuration": 276}', null, '{"results": [{"data": [{"sg_uf": "AL", "no_ente": "Poço das Trincheiras", "dt_envio": "2023-04-10 14:07:02.377", "tp_massa": "Civil", "tp_plano": "Previdenciário", "te_situacao": "Documentos Digitalizados", "dt_exercicio": 2023, "no_tipo_norma": "Lei", "no_base_calculo": "Total das Remunerações de Contribuição dos Servidores Ativos", "nr_base_calculo": 10101, "tp_beneficiario": "SERVIDOR", "nr_cnpj_entidade": "12259040000131", "dt_norma_fundamento": "2021-01-13 03:00:00.000", "nr_norma_fundamento": "331", "te_dispositivo_norma": "ART. 17 - III", "vl_anual_contribuicao": "17213893.06", "vl_mensal_contribuicao": "1324145.12"}], "resultSet": true}], "queryDuration": 276, "queueDuration": 5}');
INSERT INTO api_responses (id, description, metadata, data_dictionary, response_example) VALUES (15, 'Seleciona registro da tabela /DRAA_CUSTO_NORMAL_BENEF_CAPIT', '{"queueDuration": 13, "queryDuration": 2284}', null, '{"results": [{"data": [{"sg_uf": "SP", "no_ente": "Uchoa", "dt_envio": "2017-07-12 19:31:05.467", "tp_massa": "Civil", "tp_plano": "Previdenciário", "te_situacao": "Retificado", "dt_exercicio": 2017, "no_beneficio": "Pensão Por Morte de Aposentado por Invalidez", "no_tipo_norma": "Lei Complementar", "pc_contribuicao": 0.05, "nr_cnpj_entidade": "45111952000110", "cd_plano_beneficio": 110203, "dt_norma_fundamento": "2010-05-04 03:00:00.000", "nr_norma_fundamento": "1", "te_dispositivo_norma": "25", "vl_custo_anual_previsto": "4974.24"}], "resultSet": true}], "queryDuration": 2284, "queueDuration": 13}');
INSERT INTO api_responses (id, description, metadata, data_dictionary, response_example) VALUES (16, 'Seleciona registro da tabela /DRAA_CUSTO_NORMAL_BENEF_COB', '{"queueDuration": null, "queryDuration": null, "results": [{"resultSet": null, "data": [{"nr_cnpj_entidade": null, "sg_uf": null, "no_ente": null, "dt_exercicio": null, "dt_envio": null, "te_situacao": null, "tp_plano": null, "tp_massa": null, "no_tipo_norma": null, "nr_norma_fundamento": null, "dt_norma_fundamento": null, "te_dispositivo_norma": null, "cd_plano_beneficio": null, "no_beneficio": null, "vl_custo_anual_previsto": null, "pc_contribuicao": null}]}]', null, '{"results": [{"data": [{"sg_uf": null, "no_ente": null, "dt_envio": null, "tp_massa": null, "tp_plano": null, "te_situacao": null, "dt_exercicio": null, "no_beneficio": null, "no_tipo_norma": null, "pc_contribuicao": null, "nr_cnpj_entidade": null, "cd_plano_beneficio": null, "dt_norma_fundamento": null, "nr_norma_fundamento": null, "te_dispositivo_norma": null, "vl_custo_anual_previsto": null}], "resultSet": true}], "queryDuration": null, "queueDuration": null}');
INSERT INTO api_responses (id, description, metadata, data_dictionary, response_example) VALUES (17, 'Seleciona registro da tabela /DRAA_CUSTO_NORMAL_REP_APOS', '{"queueDuration": null, "queryDuration": null, "results": [{"resultSet": null, "data": [{"nr_cnpj_entidade": null, "sg_uf": null, "no_ente": null, "dt_exercicio": null, "dt_envio": null, "te_situacao": null, "tp_plano": null, "tp_massa": null, "no_tipo_norma": null, "nr_norma_fundamento": null, "dt_norma_fundamento": null, "te_dispositivo_norma": null, "cd_custo_normal_reparticao": null, "no_reparticao": null, "vl_pago_dois_anos_antes": null, "vl_pago_um_ano_antes": null, "vl_pago_ano_atual": null, "vl_minimo_um_ano_apos": null, "vl_previsto_um_ano_apos": null, "pc_contribuicao": null}]}]', null, '{"results": [{"data": [{"sg_uf": "PI", "no_ente": "Itainópolis", "dt_envio": "2016-01-08 01:40:53.807", "tp_massa": "Civil", "tp_plano": "Financeiro", "te_situacao": "Retificado", "dt_exercicio": 2015, "no_reparticao": "Aposentadoria Especial - Professor - Educação Infantil e Ensino Fund. e Médio", "no_tipo_norma": "Lei", "pc_contribuicao": 0, "nr_cnpj_entidade": "06553754000155", "vl_pago_ano_atual": null, "dt_norma_fundamento": "2008-03-14 03:00:00.000", "nr_norma_fundamento": "170", "te_dispositivo_norma": "ART 17", "vl_pago_um_ano_antes": null, "vl_minimo_um_ano_apos": null, "vl_pago_dois_anos_antes": null, "vl_previsto_um_ano_apos": "0", "cd_custo_normal_reparticao": 110106}], "resultSet": true}], "queryDuration": 5541, "queueDuration": 11}');
INSERT INTO api_responses (id, description, metadata, data_dictionary, response_example) VALUES (18, 'Seleciona registro da tabela /DRAA_CUSTO_NORMAL_REP_AUX', '{"queueDuration": null, "queryDuration": null, "results": [{"resultSet": null, "data": [{"nr_cnpj_entidade": null, "sg_uf": null, "no_ente": null, "dt_exercicio": null, "dt_envio": null, "te_situacao": null, "tp_plano": null, "tp_massa": null, "no_tipo_norma": null, "nr_norma_fundamento": null, "dt_norma_fundamento": null, "te_dispositivo_norma": null, "cd_custo_normal_reparticao": null, "no_reparticao": null, "vl_pago_dois_anos_antes": null, "vl_pago_um_ano_antes": null, "vl_pago_ano_atual": null, "vl_minimo_um_ano_apos": null, "vl_previsto_um_ano_apos": null, "pc_contribuicao": null}]}]', null, '{"results": [{"data": [{"sg_uf": "MG", "no_ente": "Descoberto", "dt_envio": "2018-03-27 13:10:17.177", "tp_massa": "Civil", "tp_plano": "Previdenciário", "te_situacao": "Aguardando Certificado", "dt_exercicio": 2017, "no_reparticao": "Salário Família", "no_tipo_norma": "Lei", "pc_contribuicao": 0.12, "nr_cnpj_entidade": "18558098000162", "vl_pago_ano_atual": "4660.17", "dt_norma_fundamento": "2001-05-22 03:00:00.000", "nr_norma_fundamento": "1126", "te_dispositivo_norma": "Arts. 52 a 55", "vl_pago_um_ano_antes": "4841.1", "vl_minimo_um_ano_apos": "4781.6", "vl_pago_dois_anos_antes": "4843.53", "vl_previsto_um_ano_apos": "4808.24", "cd_custo_normal_reparticao": 110304}], "resultSet": true}], "queryDuration": 322, "queueDuration": 41}');
INSERT INTO api_responses (id, description, metadata, data_dictionary, response_example) VALUES (19, '/DRAA_DADOS_CONSOLIDADOS', '{"queueDuration": null, "queryDuration": null, "results": [{"resultSet": null, "data": [{"nr_cnpj_entidade": null, "sg_uf": null, "no_ente": null, "dt_mes": null, "dt_ano": null, "dt_envio": null, "no_objeto_contratacao": null, "dt_assinatura_contrato": null, "nr_prazo_vigencia": null, "vl_mensal_contrato": null, "nr_processo": null, "no_modalidade_licitacao": null, "tp_licitacao": null, "dt_registro_responsavel": null, "no_pessoa_representante": null, "no_pessoa_responsavel": null}]}]', null, '{"results": [{"data": [{"sg_uf": "GO", "dt_ano": 2018, "dt_mes": 1, "no_ente": "Indiara", "dt_envio": "2018-02-22 21:32:52.980", "nr_processo": "216/2017", "tp_licitacao": "Menor Preco", "nr_cnpj_entidade": "00005959000110", "nr_prazo_vigencia": "9", "vl_mensal_contrato": 2200, "no_objeto_contratacao": "Outros", "no_pessoa_responsavel": null, "dt_assinatura_contrato": "2017-04-05 03:00:00.000", "dt_registro_responsavel": "2016-01-18 02:00:00.000", "no_modalidade_licitacao": "Convite", "no_pessoa_representante": null}], "resultSet": true}], "queryDuration": 455, "queueDuration": 47}');
INSERT INTO api_responses (id, description, metadata, data_dictionary, response_example) VALUES (20, '/DRAA_ENCAMINHAMENTO', '{"queueDuration": null, "queryDuration": null, "results": [{"resultSet": null, "data": [{"nr_cnpj_entidade": null, "sg_uf": null, "no_ente": null, "dt_exercicio": null, "dt_envio": null, "te_situacao": null}]}]', null, '{"results": [{"data": [{"sg_uf": "TO", "no_ente": "Figueirópolis", "dt_envio": "2018-06-26 20:37:16.597", "te_situacao": "Documentos Digitalizados", "dt_exercicio": 2017, "nr_cnpj_entidade": "00003848000174"}], "resultSet": true}], "queryDuration": 258, "queueDuration": 10}');
INSERT INTO api_responses (id, description, metadata, data_dictionary, response_example) VALUES (21, '/DRAA_ESTATISTICA', '{"queueDuration": null, "queryDuration": null, "results": [{"resultSet": null, "data": [{"nr_cnpj_entidade": null, "sg_uf": null, "no_ente": null, "dt_exercicio": null, "dt_envio": null, "te_situacao": null, "tp_plano": null, "tp_massa": null, "cnpj_orgao": null, "no_orgao": null, "cd_populacao": null, "tp_populacao": null, "no_cat_populacao": null, "no_regra_enquadramento": null, "no_criterio_aposentadoria": null, "qt_grupo_masc": null, "vl_medio_base_calculo_masc": null, "vl_idade_media_masc": null, "vl_idade_med_aposent_masc": null, "vl_idade_med_adm_masc": null, "vl_folha_mensal_masc": null, "qt_grupo_fem": null, "vl_medio_base_calculo_fem": null, "vl_idade_media_fem": null, "vl_idade_med_aposent_fem": null, "vl_idade_med_adm_fem": null, "vl_folha_mensal_fem": null}]}]', null, '{"results": [{"data": [{"sg_uf": "GO", "no_ente": "Goiânia", "dt_envio": "2023-03-29 21:39:28.143", "no_orgao": "INSTITUTO DE PREVIDÊNCIA DOS SERVIDORES DO MUNICÍPIO DE GOIÂNIA", "tp_massa": "Civil", "tp_plano": "Previdenciário", "cnpj_orgao": "08948407000157", "te_situacao": "Documentos Digitalizados", "cd_populacao": 3230300, "dt_exercicio": 2023, "qt_grupo_fem": 1622, "tp_populacao": "Aposentados", "qt_grupo_masc": 81, "no_cat_populacao": "PROFESSORES DA EDUC. INFANTIL E DO ENSINO FUND. E MÉDIO", "nr_cnpj_entidade": "01612092000123", "vl_idade_media_fem": 73.77, "vl_folha_mensal_fem": 13671059.44, "vl_idade_media_masc": 73.57, "vl_folha_mensal_masc": 934762.68, "vl_idade_med_adm_fem": 33.91, "vl_idade_med_adm_masc": 35.82, "no_regra_enquadramento": "Por Tempo de Contribuição", "vl_idade_med_aposent_fem": 0, "no_criterio_aposentadoria": null, "vl_idade_med_aposent_masc": 0, "vl_medio_base_calculo_fem": 8428.52, "vl_medio_base_calculo_masc": 11540.28}], "resultSet": true}], "queryDuration": 552, "queueDuration": 12}');
INSERT INTO api_responses (id, description, metadata, data_dictionary, response_example) VALUES (22, '/DRAA_FLUXO_ATUARIAL', '{"queueDuration": null, "queryDuration": null, "results": [{"resultSet": null, "data": [{"nr_cnpj_entidade": null, "sg_uf": null, "no_ente": null, "tp_plano": null, "tp_massa": null, "dt_exercicio": null, "nr_fluxo": null, "no_fluxo": null, "vl_projetado": null}]}]', null, '{"results": [{"data": [{"sg_uf": "BA", "no_ente": "Ponto Novo", "no_fluxo": "Benefícios a Conceder - Contribuições dos Aposentados", "nr_fluxo": 123000, "tp_massa": "Civil", "tp_plano": "Previdenciário", "dt_exercicio": 2020, "vl_projetado": 0, "nr_cnpj_entidade": "16444143000122"}], "resultSet": true}], "queryDuration": 272, "queueDuration": 11}');
INSERT INTO api_responses (id, description, metadata, data_dictionary, response_example) VALUES (23, '/DRAA_FORMA_AMORTIZACAO', '{"queueDuration": null, "queryDuration": null, "results": [{"resultSet": null, "data": [{"nr_cnpj_entidade": null, "sg_uf": null, "no_ente": null, "dt_exercicio": null, "dt_envio": null, "te_situacao": null, "tp_plano": null, "tp_massa": null, "cd_demonstrativo": null, "ds_item_resultado": null, "vl_geracao_atual": null}]}]', null, '{"results": [{"data": [{"sg_uf": "TO", "no_ente": "Figueirópolis", "dt_envio": "2018-06-26 20:37:16.597", "tp_massa": "Civil", "tp_plano": "Previdenciário", "te_situacao": "Documentos Digitalizados", "dt_exercicio": 2017, "cd_demonstrativo": 109001, "nr_cnpj_entidade": "00003848000174", "vl_geracao_atual": "25349292.72", "ds_item_resultado": "Valor Atual dos Salários Futuros"}], "resultSet": true}], "queryDuration": 2214, "queueDuration": 4}');
INSERT INTO api_responses (id, description, metadata, data_dictionary, response_example) VALUES (24, '/DRAA_HIPOTESE_ATUARIAL', '{"queueDuration": null, "queryDuration": null, "results": [{"resultSet": null, "data": [{"nr_cnpj_entidade": null, "sg_uf": null, "no_ente": null, "dt_exercicio": null, "dt_envio": null, "te_situacao": null, "tp_plano": null, "tp_massa": null, "cd_hipotese_demografica": null, "ds_hipotese_demografica": null, "tp_unidade": null, "te_hipotese_demografica": null, "vl_previsto_dois_antes": null, "vl_ocorrido_dois_antes": null, "vl_previsto_um_antes": null, "vl_ocorrido_um_antes": null, "vl_previsto_ano_avaliacao": null, "vl_ocorrido_ano_avaliacao": null, "vl_perspectiva_longo_prazo": null, "te_justificativa_tecnica": null}]}]', null, '{"results": [{"data": [{"sg_uf": "GO", "no_ente": "Mineiros", "dt_envio": "2017-06-21 17:14:56.713", "tp_massa": "Civil", "tp_plano": "Previdenciário", "tp_unidade": "TEXTO", "te_situacao": "Documentos Digitalizados", "dt_exercicio": 2017, "nr_cnpj_entidade": "02316537000190", "vl_ocorrido_um_antes": "Não se aplica", "vl_previsto_um_antes": "Não se aplica", "vl_ocorrido_dois_antes": "Não se aplica", "vl_previsto_dois_antes": "Não se aplica", "cd_hipotese_demografica": 30001, "ds_hipotese_demografica": "Projeção da Taxa de Rotatividade", "te_hipotese_demografica": "1", "te_justificativa_tecnica": null, "vl_ocorrido_ano_avaliacao": "0,70", "vl_previsto_ano_avaliacao": "1", "vl_perspectiva_longo_prazo": null}], "resultSet": true}], "queryDuration": 274, "queueDuration": 2}');
INSERT INTO api_responses (id, description, metadata, data_dictionary, response_example) VALUES (25, '/DRAA_HIPOTESE_BIOMETRICA', '{"queueDuration": null, "queryDuration": null, "results": [{"resultSet": null, "data": [{"nr_cnpj_entidade": null, "sg_uf": null, "no_ente": null, "dt_exercicio": null, "dt_envio": null, "te_situacao": null, "tp_plano": null, "tp_massa": null, "cd_hipotese_biometrica_masc": null, "ds_hipotese_biometrica_masc": null, "cd_tipo_tabua_masc": null, "tp_tabua_masc": null, "nr_even_prev_menos_dois_anos_m": null, "nr_even_ocor_menos_dois_anos_m": null, "nr_even_prev_menos_um_ano_m": null, "nr_even_ocor_menos_um_ano_m": null, "nr_even_prev_menos_ano_aval_m": null, "nr_even_ocor_menos_ano_aval_m": null, "ds_justificativa_tecnica_masc": null, "cd_hipotese_biometrica_fem": null, "ds_hipotese_biometrica_fem": null, "dt_exercicio_inicial": null, "tp_sexo": null, "cd_tipo_tabua_fem": null, "tp_tabua_fem": null, "nr_even_prev_menos_dois_anos_f": null, "nr_even_ocor_menos_dois_anos_f": null, "nr_even_prev_menos_um_ano_f": null, "nr_even_ocor_menos_um_ano_f": null, "nr_even_prev_menos_ano_aval_f": null, "nr_even_ocor_menos_ano_aval_f": null, "ds_justificativa_tecnica_fem": null}]}]', null, '{"results": [{"data": [{"sg_uf": "PA", "no_ente": "Abaetetuba", "tp_sexo": "AMBOS", "dt_envio": "2021-08-06 19:30:58.783", "tp_massa": "Civil", "tp_plano": "Financeiro", "te_situacao": "Documentos Digitalizados", "dt_exercicio": 2021, "tp_tabua_fem": "Tábua de Entrada em Invalidez", "tp_tabua_masc": "Tábua de Entrada em Invalidez", "nr_cnpj_entidade": "05105127000199", "cd_tipo_tabua_fem": 4000, "cd_tipo_tabua_masc": 4000, "dt_exercicio_inicial": 2015, "cd_hipotese_biometrica_fem": 4101, "ds_hipotese_biometrica_fem": "Álvaro Vindas", "cd_hipotese_biometrica_masc": 4101, "ds_hipotese_biometrica_masc": "Álvaro Vindas", "nr_even_ocor_menos_um_ano_f": 0, "nr_even_ocor_menos_um_ano_m": 0, "nr_even_prev_menos_um_ano_f": 0, "nr_even_prev_menos_um_ano_m": 0, "ds_justificativa_tecnica_fem": "Não se aplica tabua ambos os sexos", "ds_justificativa_tecnica_masc": "Não temos massa critica para efetuar teste de aderência", "nr_even_ocor_menos_ano_aval_f": 0, "nr_even_ocor_menos_ano_aval_m": 0, "nr_even_prev_menos_ano_aval_f": 0, "nr_even_prev_menos_ano_aval_m": 0, "nr_even_ocor_menos_dois_anos_f": 0, "nr_even_ocor_menos_dois_anos_m": 0, "nr_even_prev_menos_dois_anos_f": 0, "nr_even_prev_menos_dois_anos_m": 0}], "resultSet": true}], "queryDuration": 897, "queueDuration": 37}');
INSERT INTO api_responses (id, description, metadata, data_dictionary, response_example) VALUES (26, '/DRAA_NOTIFICACAO', '{"queueDuration": null, "queryDuration": null, "results": [{"resultSet": null, "data": [{"nr_cnpj_entidade": null, "sg_uf": null, "no_ente": null, "nr_notificacao": null, "no_tipo_documento": null, "no_item_analise": null, "no_situacao_item_analise": null, "dt_notificao": null, "dt_preclusao": null, "dt_resposta": null, "nr_prazo_resposta": null}]}]', null, '{"results": [{"data": [{"sg_uf": "SP", "no_ente": "São Paulo", "dt_resposta": null, "dt_notificao": "2022-04-05 19:06:07.123", "dt_preclusao": "2022-05-05 03:00:00.000", "nr_notificacao": "089768.01/2022", "no_item_analise": "Consistência - Segregação da Massa", "nr_cnpj_entidade": "46395000000139", "no_tipo_documento": "DRAA", "nr_prazo_resposta": 30, "no_situacao_item_analise": "Resposta analisada. Item sem pendencia"}], "resultSet": true}], "queryDuration": 91, "queueDuration": 48}');
INSERT INTO api_responses (id, description, metadata, data_dictionary, response_example) VALUES (27, '/DRAA_ORGAO_ENTIDADE', '{"queueDuration": null, "queryDuration": null, "results": [{"resultSet": null, "data": [{"nr_cnpj_entidade": null, "sg_uf": null, "no_ente": null, "dt_exercicio": null, "dt_envio": null, "te_situacao": null, "tp_plano": null, "tp_massa": null, "cnpj_orgao": null, "no_orgao": null, "dt_competencia_base_cadastral": null, "tp_poder": null, "tp_orgao": null}]}]', null, '{"results": [{"data": [{"sg_uf": "TO", "no_ente": "Figueirópolis", "dt_envio": "2018-06-26 20:37:16.597", "no_orgao": "Prefeitura Municipal de Figueiropolis/TO", "tp_massa": "Civil", "tp_orgao": "Administração Direta", "tp_plano": "Previdenciário", "tp_poder": "Executivo", "cnpj_orgao": "00003848000174", "te_situacao": "Documentos Digitalizados", "dt_exercicio": 2017, "nr_cnpj_entidade": "00003848000174", "dt_competencia_base_cadastral": "12/2017"}], "resultSet": true}], "queryDuration": 1254, "queueDuration": 21}');
INSERT INTO api_responses (id, description, metadata, data_dictionary, response_example) VALUES (28, '/DRAA_PARECER_ATUARIAL', '{"queueDuration": null, "queryDuration": null, "results": [{"resultSet": null, "data": [{"nr_cnpj_entidade": null, "sg_uf": null, "no_ente": null, "dt_exercicio": null, "dt_envio": null, "te_situacao": null, "tp_plano": null, "tp_massa": null, "cd_tema": null, "no_tema": null, "te_parecer": null}]}]', null, '{"results": [{"data": [{"sg_uf": "PI", "cd_tema": 55001, "no_ente": "Colônia do Gurguéia", "no_tema": "Plano de custeio a ser implementado e medidas para manutenção do equilíbrio financeiro e atuarial", "dt_envio": "2021-05-13 19:50:50.353", "tp_massa": "Civil", "tp_plano": "Previdenciário", "te_parecer": "O plano de custeio para 2021 prevê a alíquota de 14% para o ente público, a título de contribuição normal e de 14% para os segurados, sendo que para os inativos e pensionistas a alíquota incidirá sobre a parcela do benefício que exceder o teto do Regime Geral de Previdência Social. Além da contribuição normal, o ente público contribuirá com as alíquotas definidas no plano de amortização que consta deste DRAA.", "te_situacao": "Documentos Digitalizados", "dt_exercicio": 2021, "nr_cnpj_entidade": "41522350000103"}], "resultSet": true}], "queryDuration": 238, "queueDuration": 20}');
INSERT INTO api_responses (id, description, metadata, data_dictionary, response_example) VALUES (29, '/DRAA_PLANO_AMORTIZACAO', '{"queueDuration": null, "queryDuration": null, "results": [{"resultSet": null, "data": [{"nr_cnpj_entidade": null, "sg_uf": null, "no_ente": null, "dt_exercicio": null, "dt_envio": null, "te_situacao": null, "tp_plano": null, "tp_massa": null, "dt_ano": null, "tx_juros": null, "vl_aporte": null, "vl_aliquotas": null, "vl_base_calculo": null, "vl_saldo_inicial": null, "vl_pagamentos": null, "vl_saldo_final": null, "vl_juros": null, "vl_amortizacao": null}]}]', null, '{"results": [{"data": [{"sg_uf": "SP", "dt_ano": 2043, "no_ente": "Olímpia", "dt_envio": "2018-06-11 14:21:03.047", "tp_massa": "Civil", "tp_plano": "Previdenciário", "tx_juros": 6, "vl_juros": "-438768.1", "vl_aporte": null, "te_situacao": "Documentos Digitalizados", "dt_exercicio": 2018, "vl_aliquotas": "6", "vl_pagamentos": "-3407700", "vl_amortizacao": "-2968931.9", "vl_saldo_final": "7751569.82", "vl_base_calculo": "56795000", "nr_cnpj_entidade": "46596151000155", "vl_saldo_inicial": "10720501.72"}], "resultSet": true}], "queryDuration": 684, "queueDuration": 3}');
INSERT INTO api_responses (id, description, metadata, data_dictionary, response_example) VALUES (30, '/DRAA_PLANO_AMORTIZACAO_DEFICIT', '{"queueDuration": null, "queryDuration": null, "results": [{"resultSet": null, "data": [{"nr_cnpj_entidade": null, "sg_uf": null, "no_ente": null, "dt_exercicio": null, "dt_envio": null, "te_situacao": null, "tp_plano": null, "tp_massa": null, "nr_base_calculo": null, "no_base_calculo": null}]}]', null, '{"results": [{"data": [{"sg_uf": "AL", "no_ente": "Poço das Trincheiras", "dt_envio": "2023-04-10 14:07:02.377", "tp_massa": "Civil", "tp_plano": "Previdenciário", "te_situacao": "Documentos Digitalizados", "dt_exercicio": 2023, "no_base_calculo": "Total das Remunerações de Contribuição dos Servidores Ativos", "nr_base_calculo": 10101, "nr_cnpj_entidade": "12259040000131"}], "resultSet": true}], "queryDuration": 253, "queueDuration": 8}');
INSERT INTO api_responses (id, description, metadata, data_dictionary, response_example) VALUES (31, '/DRAA_PLANO_BENEFICIO', '{"queueDuration": null, "queryDuration": null, "results": [{"resultSet": null, "data": [{"nr_cnpj_entidade": null, "sg_uf": null, "no_ente": null, "dt_exercicio": null, "dt_envio": null, "te_situacao": null, "tp_plano": null, "tp_massa": null, "no_tipo_norma": null, "nr_norma_fundamento": null, "dt_norma_fundamento": null, "te_dispositivo_norma": null, "nr_plano_benefico": null, "no_beneficio_plano": null, "nr_regime_financeiro": null, "ds_regime_financeiro": null, "ds_metodo_financiamento": null}]}]', null, '{"results": [{"data": [{"sg_uf": "GO", "no_ente": "Goianésia", "dt_envio": "2021-05-05 12:13:37.617", "tp_massa": "Civil", "tp_plano": "Previdenciário", "te_situacao": "Documentos Digitalizados", "dt_exercicio": 2021, "no_tipo_norma": "Lei", "nr_cnpj_entidade": "01065846000172", "no_beneficio_plano": "Aposentadorias Programadas (Por Idade, Tempo de Contribuição e Compulsória)", "nr_plano_beneficio": 110102, "dt_norma_fundamento": "2005-12-09 02:00:00.000", "nr_norma_fundamento": "2380", "ds_regime_financeiro": "REGIME FINANCEIRO DE CAPITALIZAÇÃO - PRÊMIO NIVELADO INDIVIDUAL", "nr_regime_financeiro": 102, "te_dispositivo_norma": "Art. 15", "ds_metodo_financiamento": null}], "resultSet": true}], "queryDuration": 351, "queueDuration": 20}');
INSERT INTO api_responses (id, description, metadata, data_dictionary, response_example) VALUES (32, '/DRAA_PLANO_CUSTEIO', '{"queueDuration": null, "queryDuration": null, "results": [{"resultSet": null, "data": [{"nr_cnpj_entidade": null, "sg_uf": null, "no_ente": null, "dt_exercicio": null, "dt_envio": null, "te_situacao": null, "tp_plano": null, "tp_massa": null, "tp_contribuicao": null, "vl_anual_base_calculo": null, "vl_aliquota": null, "vl_contribuicao_esperada": null, "vl_aliquota_definida": null, "vl_contribuicao_definida": null}]}]', null, '{"results": [{"data": [{"sg_uf": "PA", "no_ente": "Abaetetuba", "dt_envio": "2021-08-06 19:30:58.783", "tp_massa": "Civil", "tp_plano": "Financeiro", "te_situacao": "Documentos Digitalizados", "vl_aliquota": "11", "dt_exercicio": 2021, "tp_contribuicao": "Aposentados", "nr_cnpj_entidade": "05105127000199", "vl_aliquota_definida": "14", "vl_anual_base_calculo": "0", "vl_contribuicao_definida": "0", "vl_contribuicao_esperada": "0"}], "resultSet": true}], "queryDuration": 421, "queueDuration": 26}');
INSERT INTO api_responses (id, description, metadata, data_dictionary, response_example) VALUES (33, '/DRAA_RETIFICACAO_NOTIFICACAO', '{"queueDuration": null, "queryDuration": null, "results": [{"resultSet": null, "data": [{"nr_cnpj_entidade": null, "sg_uf": null, "no_ente": null, "dt_exercicio": null, "dt_envio": null, "te_situacao": null, "tp_plano": null, "tp_massa": null, "in_retificacao": null, "in_motivo_notificacao": null, "nr_notificacao": null}]}]', null, '{"results": [{"data": [{"sg_uf": "SP", "no_ente": "Cândido Rodrigues", "dt_envio": "2018-08-06 12:41:11.990", "tp_massa": "Civil", "tp_plano": "Previdenciário", "te_situacao": "Documentos Digitalizados", "dt_exercicio": 2018, "in_retificacao": "Não", "nr_notificacao": null, "nr_cnpj_entidade": "45374261000100", "in_motivo_notificacao": null}], "resultSet": true}], "queryDuration": 203, "queueDuration": 27}');
INSERT INTO api_responses (id, description, metadata, data_dictionary, response_example) VALUES (34, '/DRAA_SEGREGACAO_MASSA', '{"queueDuration": null, "queryDuration": null, "results": [{"resultSet": null, "data": [{"nr_cnpj_entidade": null, "sg_uf": null, "no_ente": null, "dt_exercicio": null, "tp_massa": null, "te_situacao": null, "tp_plano": null, "no_previdencia_complementar": null, "no_beneficio_tesouro": null, "no_tipo_norma": null, "nr_norma_fundamento": null, "dt_norma_fundamento": null, "te_dispositivo_norma": null, "no_segregacao_massa": null, "dt_ingresso_segurado": null, "nr_idade_segurado": null, "in_segurado_servidor": null, "in_segurado_aposentado": null, "in_segurado_pensionista": null, "no_atuario_responsavel": null, "nr_registro_prof_atuario": null, "tp_documento": null, "nr_documento": null, "dt_documento": null}]}]', null, '{"results": [{"data": [{"sg_uf": "SP", "no_ente": "Cândido Rodrigues", "tp_massa": "Civil", "tp_plano": "Previdenciário", "te_situacao": "Documentos Digitalizados", "dt_documento": "", "dt_exercicio": 2016, "nr_documento": "", "tp_documento": "", "no_tipo_norma": null, "nr_cnpj_entidade": "45374261000100", "nr_idade_segurado": "", "dt_norma_fundamento": null, "no_segregacao_massa": "Não Possui", "nr_norma_fundamento": null, "dt_ingresso_segurado": "", "in_segurado_servidor": "", "no_beneficio_tesouro": "Não", "te_dispositivo_norma": null, "in_segurado_aposentado": "", "no_atuario_responsavel": "", "in_segurado_pensionista": "", "nr_registro_prof_atuario": "", "no_previdencia_complementar": "Não"}], "resultSet": true}], "queryDuration": 463, "queueDuration": 10}');
INSERT INTO api_responses (id, description, metadata, data_dictionary, response_example) VALUES (35, '/DRAA_VALORES_COMPROMISSOS', '{"queueDuration": null, "queryDuration": null, "results": [{"resultSet": null, "data": [{"nr_cnpj_entidade": null, "sg_uf": null, "no_ente": null, "dt_exercicio": null, "tp_massa": null, "te_situacao": null, "tp_plano": null, "cd_demonstrativo": null, "ds_item_resultado": null, "no_categoria_demonstrativo": null, "vl_geracao_atual": null, "vl_geracao_futura": null}]}]', null, '{"results": [{"data": [{"sg_uf": "GO", "no_ente": "São Luiz do Norte", "dt_envio": "2017-05-22 13:11:10.897", "tp_massa": "Civil", "tp_plano": "Previdenciário", "te_situacao": "Documentos Digitalizados", "dt_exercicio": 2016, "cd_demonstrativo": 221000, "nr_cnpj_entidade": "25043639000185", "vl_geracao_atual": "19129348.93", "ds_item_resultado": "Benefícios a Conceder - Encargos -  Aposentadorias Programadas", "vl_geracao_futura": "0", "no_categoria_demonstrativo": "Resultado"}], "resultSet": true}], "queryDuration": 575, "queueDuration": 9}');
INSERT INTO api_responses (id, description, metadata, data_dictionary, response_example) VALUES (36, '/RPPS_ALIQUOTA', '{"queueDuration": null, "queryDuration": null, "results": [{"resultSet": null, "data": [{"nr_cnpj_entidade": null, "no_ente": null, "sg_uf": null, "ds_plano_segregacao": null, "no_sujeito_passivo": null, "vl_aliquota": null, "dt_inicio_vigencia": null, "dt_fim_vigencia": null, "id_vigente": null, "tp_regime": null}]}]', null, '{"results": [{"data": [{"sg_uf": "TO", "no_ente": "Figueirópolis", "tp_regime": "RPPS", "id_vigente": "NÃO VIGENTE", "vl_aliquota": "11.00", "dt_fim_vigencia": "2017-04-08 03:00:00.000", "nr_cnpj_entidade": "00003848000174", "dt_inicio_vigencia": "2017-01-09 02:00:00.000", "no_sujeito_passivo": "Aposentados", "ds_plano_segregacao": "Fundo em Capitalização"}], "resultSet": true}], "queryDuration": 661, "queueDuration": 2}');
INSERT INTO api_responses (id, description, metadata, data_dictionary, response_example) VALUES (37, '/RPPS_CRP', '{"queueDuration": null, "queryDuration": null, "results": [{"resultSet": null, "data": [{"nr_cnpj_entidade": null, "no_ente": null, "sg_uf": null, "nr_crp": null, "ds_situacao": null, "dt_emissao": null, "dt_validade": null, "tp_crp": null}]}]', null, '{"results": [{"data": [{"sg_uf": "TO", "nr_crp": "989679-103544", "tp_crp": "VENCIDO", "no_ente": "Rio Sono", "dt_emissao": "05/03/2012", "ds_situacao": "ADMINISTRATIVO", "dt_validade": "01/09/2012", "nr_cnpj_entidade": "00000729000168"}], "resultSet": true}], "queryDuration": 250, "queueDuration": 8}');
INSERT INTO api_responses (id, description, metadata, data_dictionary, response_example) VALUES (38, '/RPPS_REGIME_PREVIDENCIARIO', '{"queueDuration": null, "queryDuration": null, "results": [{"resultSet": null, "data": [{"nr_cnpj_entidade": null, "sg_uf": null, "no_ente": null, "tp_regime": null, "dt_inicio": null, "dt_fim": null, "no_tipo_legislacao": null, "nr_legislacao": null, "dt_legislacao": null, "te_ementa": null, "tp_vinculo_legislacao": null}]}]', null, '{"results": [{"data": [{"sg_uf": "TO", "dt_fim": null, "no_ente": "Rio Sono", "dt_inicio": "2002-04-23 03:00:00.000", "te_ementa": "RGP", "tp_regime": "RGPS", "dt_legislacao": "2002-04-23 03:00:00.000", "nr_legislacao": "84", "nr_cnpj_entidade": "00000729000168", "no_tipo_legislacao": "LEI", "tp_vinculo_legislacao": "Criação do Regime"}], "resultSet": true}], "queryDuration": 3043, "queueDuration": 26}');


-- insert tags
INSERT INTO tags (id, name, description)
VALUES (1, 'cadprev', 'Tag cadprev');


-- insert api_tags
INSERT INTO api_tags (id, api_id, tag_id)
VALUES (1, 1, 1);
